import { notFound } from "next/navigation";
import { Bell, CheckCircle2, Clock3, Download, FileText } from "lucide-react";
import { DashboardShell } from "@/components/DashboardShell";

const sections: Record<string,{title:string;subtitle:string;items:{title:string;meta:string;action:string}[]}> = {
  formations:{title:"Mes formations",subtitle:"Retrouvez uniquement les parcours auxquels vous avez accès.",items:[{title:"Comptabilité générale et pratique",meta:"Progression 65 % · Dernière activité hier",action:"Continuer"},{title:"Fiscalité marocaine",meta:"Progression 42 % · Dernière activité lundi",action:"Continuer"},{title:"Excel professionnel",meta:"Progression 80 % · Dernière activité vendredi",action:"Continuer"}]},
  agenda:{title:"Mon agenda",subtitle:"Vos prochaines séances de formation.",items:[{title:"TVA : champ d'application",meta:"4 août 2026 · 18h30 · Google Meet",action:"Voir la séance"},{title:"Travaux d'inventaire",meta:"7 août 2026 · 19h00 · Google Meet",action:"Voir la séance"},{title:"Tableaux croisés dynamiques",meta:"11 août 2026 · 18h30 · En ligne",action:"Voir la séance"}]},
  supports:{title:"Supports",subtitle:"Tous les documents autorisés pour vos formations.",items:[{title:"Guide pratique de la TVA",meta:"PDF · 2,4 Mo · Fiscalité marocaine",action:"Télécharger"},{title:"Cas pratique : société Atlas",meta:"Excel · 680 Ko · Comptabilité",action:"Télécharger"},{title:"Modèle de tableau de bord",meta:"Excel · 1,1 Mo · Excel professionnel",action:"Télécharger"}]},
  qcm:{title:"QCM & résultats",subtitle:"Évaluez vos acquis et consultez vos résultats.",items:[{title:"QCM · Principes comptables",meta:"Score 85 % · Réussi",action:"Voir le résultat"},{title:"QCM · TVA",meta:"Nouvelle tentative disponible",action:"Commencer"},{title:"QCM · Fonctions avancées Excel",meta:"Score 92 % · Réussi",action:"Voir le résultat"}]},
  attestations:{title:"Attestations",subtitle:"Vos attestations disponibles et à venir.",items:[{title:"Excel professionnel",meta:"Attestation LF-2026-0184 · Disponible",action:"Télécharger"},{title:"Comptabilité générale et pratique",meta:"Disponible après validation du parcours",action:"Voir les conditions"}]},
  paiements:{title:"Paiements",subtitle:"Consultez votre situation financière en toute transparence.",items:[{title:"Comptabilité générale et pratique",meta:"2 400 MAD · Payé",action:"Voir le reçu"},{title:"Fiscalité marocaine",meta:"1 100 / 2 200 MAD · Partiellement payé",action:"Voir le détail"}]},
  profil:{title:"Mon profil",subtitle:"Vos informations personnelles et professionnelles.",items:[{title:"Nadia Berrada",meta:"nadia@example.com · Casablanca · Responsable administrative",action:"Modifier le profil"}]},
};

export default async function StudentSection({params}:{params:Promise<{section:string}>}) { const {section}=await params; const data=sections[section]; if(!data) notFound(); return <DashboardShell><header className="dash-header"><div><small>ESPACE STAGIAIRE</small><h1>{data.title}</h1></div><div className="dash-user"><Bell size={18}/><span>NB</span></div></header><div className="dash-section-title"><div><h2>{data.title}</h2><p className="dash-subtitle">{data.subtitle}</p></div></div><section className="dash-card section-list">{data.items.map(item=><article className="section-row" key={item.title}><span className="learning-icon">{section==="supports"?<FileText size={19}/>:section==="agenda"?<Clock3 size={19}/>:<CheckCircle2 size={19}/>}</span><div><h3>{item.title}</h3><p>{item.meta}</p></div><button type="button" className="row-action">{section==="supports"&&<Download size={15}/>} {item.action}</button></article>)}</section></DashboardShell>; }
