import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Check, Clock3, Globe2, Monitor, Signal } from "lucide-react";
import { CourseCover } from "@/components/CourseCard";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { WhatsApp } from "@/components/WhatsApp";
import { formations, getFormation } from "@/data/formations";
import { siteConfig } from "@/data/site";

export function generateStaticParams() { return formations.map(({slug}) => ({slug})); }
export async function generateMetadata({params}: {params: Promise<{slug: string}>}): Promise<Metadata> { const {slug} = await params; const formation = getFormation(slug); return formation ? {title: formation.title, description: formation.shortDescription} : {}; }

export default async function FormationPage({params}: {params: Promise<{slug: string}>}) {
  const {slug} = await params; const formation = getFormation(slug); if (!formation) notFound();
  const whatsappText = encodeURIComponent(`Bonjour, je souhaite m’inscrire à la formation « ${formation.title} ». Pouvez-vous me donner plus d’informations ?`);
  return <><Header/><main><section className="detail-hero"><div className="container"><Link href="/formations" className="back-link"><ArrowLeft/> Retour aux formations</Link><div className="detail-hero-grid"><div><span className="category-badge">{formation.category}</span><h1>{formation.title}</h1><p>{formation.description}</p><div className="detail-meta"><span><Clock3/>{formation.duration}</span><span><Monitor/>{formation.format}</span><span><Signal/>{formation.level}</span><span><Globe2/>{formation.language}</span></div><div className="hero-actions"><Link href={`/inscription?formation=${formation.slug}`} className="button primary">Demander une inscription</Link>{siteConfig.whatsappNumber && <a className="button whatsapp-button" href={`https://wa.me/${siteConfig.whatsappNumber}?text=${whatsappText}`} target="_blank" rel="noreferrer">Écrire sur WhatsApp</a>}</div></div><CourseCover formation={formation} className="detail-cover"/></div></div></section>
    <section className="section"><div className="container detail-layout"><div className="detail-content"><section><h2>Objectifs de la formation</h2><ul className="check-list">{formation.objectives.map((item) => <li key={item}><Check/>{item}</li>)}</ul></section><section><h2>Programme</h2><div className="accordion-list">{formation.modules.map((module, index) => <details key={module.title} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{module.title}</summary><ul>{module.content.map((item) => <li key={item}>{item}</li>)}</ul></details>)}</div></section><section className="two-columns"><div><h2>À qui s’adresse cette formation ?</h2><ul>{formation.audience.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2>Prérequis</h2><ul>{formation.prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section><h2>Déroulement</h2><div className="feature-list">{formation.features.map((item) => <span key={item}><Check/>{item}</span>)}</div></section>{formation.trainer && <section><h2>Votre formateur</h2><div className="trainer-block"><strong>{formation.trainer.name}</strong><span>{formation.trainer.role}</span><p>{formation.trainer.bio}</p></div></section>}</div><aside className="detail-aside"><h2>Informations pratiques</h2><dl><div><dt>Durée</dt><dd>{formation.duration}</dd></div><div><dt>Rythme</dt><dd>{formation.sessions}</dd></div><div><dt>Format</dt><dd>{formation.format}</dd></div><div><dt>Niveau</dt><dd>{formation.level}</dd></div>{formation.price && <div><dt>Tarif</dt><dd>{formation.price}</dd></div>}{formation.nextSession && <div><dt>Prochaine session</dt><dd>{formation.nextSession}</dd></div>}</dl><Link href={`/inscription?formation=${formation.slug}`} className="button primary full-button">S’inscrire</Link></aside></div></section></main><Footer/><WhatsApp course={formation.title}/></>;
}
