import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Award, BookOpenCheck, Check, CheckCircle2, ChevronDown, Clock3, Headphones, Layers3, MessageCircle, MonitorPlay, PlayCircle, Target, UserRoundCheck } from "lucide-react";
import { Header } from "@/components/Header";import { Footer } from "@/components/Footer";import { WhatsApp } from "@/components/WhatsApp";import { CourseCover } from "@/components/CourseCard";import { courses } from "@/data/courses";import { siteConfig } from "@/data/site";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const course=courses.find(c=>c.slug===slug);return {title:course?.title??"Formation",description:course?.description}}
export default async function CoursePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const course=courses.find(c=>c.slug===slug);if(!course)notFound();const whatsapp=encodeURIComponent(`Bonjour, je souhaite avoir plus d'informations sur la formation ${course.title}.`);return <><Header/><main>
  <section className="course-landing-hero"><div className="course-hero-glow"/><div className="container course-landing-grid"><div><div className="breadcrumbs"><Link href="/">Accueil</Link><span>/</span><Link href="/formations">Formations</Link><span>/</span><b>{course.title}</b></div><span className="hero-badge dark"><BookOpenCheck/>{course.category}</span><h1>{course.title}</h1><p>{course.description}</p><div className="course-hero-facts"><span><Clock3/><b>{course.duration}</b><small>Durée</small></span><span><MonitorPlay/><b>{course.format}</b><small>Format</small></span><span><Target/><b>{course.level}</b><small>Niveau</small></span></div><div className="hero-actions"><Link href={`/inscription?formation=${course.slug}`} className="button primary">S&apos;inscrire à la formation <ArrowRight/></Link><a href={`https://wa.me/${siteConfig.whatsappNumber}?text=${whatsapp}`} target="_blank" rel="noreferrer" className="button whatsapp-button"><MessageCircle/> WhatsApp</a></div></div><div className="course-hero-image"><CourseCover index={course.coverIndex}/><div className="image-caption"><span><PlayCircle/>Sessions interactives</span><span><Award/>Attestation de formation</span></div></div></div></section>

  <nav className="course-subnav"><div className="container"><a href="#presentation">Présentation</a><a href="#objectifs">Objectifs</a><a href="#programme">Programme</a><a href="#methode">Méthode</a><a href="#infos">Infos pratiques</a></div></nav>

  <section className="section course-content"><div className="container course-sales-grid"><div className="course-main-content"><article id="presentation" className="sales-block"><span className="section-kicker">La formation</span><h2>Transformez les notions en <span>savoir-faire concret</span></h2><p>Ce parcours alterne apports structurés, démonstrations, échanges en direct et mises en pratique. Vous progressez avec des supports accessibles depuis votre espace personnel.</p><div className="presentation-points"><span><CheckCircle2/>Séances animées en direct</span><span><CheckCircle2/>Enregistrements disponibles</span><span><CheckCircle2/>Exercices et cas pratiques</span><span><CheckCircle2/>Suivi de la progression</span></div></article>
  <article id="objectifs" className="sales-block tinted"><div><span className="section-kicker">Vos acquis</span><h2>Objectifs pédagogiques</h2></div><div className="objective-list">{course.objectives.map((o,i)=><span key={o}><b>{String(i+1).padStart(2,"0")}</b>{o}</span>)}</div></article>
  <article className="sales-block"><span className="section-kicker">Public concerné</span><h2>À qui s’adresse cette formation ?</h2><div className="audience-grid">{course.audience.map(a=><span key={a}><UserRoundCheck/>{a}</span>)}</div></article>
  <article id="programme" className="sales-block"><span className="section-kicker">Le programme</span><h2>Un parcours détaillé et progressif</h2><p>Ouvrez chaque module pour découvrir les sujets abordés.</p><div className="program-accordion">{course.program.map((module,i)=><details key={module.title} open={i===0}><summary><span><b>Module {String(i+1).padStart(2,"0")}</b>{module.title}</span><ChevronDown/></summary><ul>{module.lessons.map(lesson=><li key={lesson}><Check/>{lesson}</li>)}</ul></details>)}</div></article>
  <article id="methode" className="sales-block"><span className="section-kicker">Notre méthode</span><h2>Apprendre en faisant</h2><div className="method-grid"><span><i><MonitorPlay/></i><b>Cours en direct</b><small>Posez vos questions et échangez avec le formateur.</small></span><span><i><Layers3/></i><b>Cas pratiques</b><small>Travaillez sur des situations proches de l’entreprise.</small></span><span><i><Headphones/></i><b>Accompagnement</b><small>Avancez avec un cadre et des objectifs clairs.</small></span></div></article>
  <article className="sales-block trainer-block"><div className="trainer-avatar">LF</div><div><span className="section-kicker">Votre formateur</span><h2>Un professionnel du terrain</h2><p>Le profil du formateur sera affiché ici dès son affectation à la prochaine session.</p></div></article>
  <article className="sales-block faq-block"><span className="section-kicker">Questions fréquentes</span><h2>Avant de commencer</h2>{[["Les cours sont-ils enregistrés ?","Oui, les enregistrements sont prévus pour permettre de revoir les séances."],["Quels supports sont fournis ?","Les supports, exercices et ressources du parcours sont accessibles depuis l’espace stagiaire."],["Une attestation est-elle prévue ?","Une attestation de formation est disponible selon les conditions de validation du parcours."]].map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</article></div>
  <aside id="infos" className="course-info-card"><span className="info-label">Informations pratiques</span><h3>{course.title}</h3><div className="info-lines"><span><Clock3/><div><small>Durée</small><b>{course.duration}</b></div></span><span><MonitorPlay/><div><small>Format</small><b>{course.format}</b></div></span><span><Layers3/><div><small>Programme</small><b>{course.modules} modules</b></div></span><span><Award/><div><small>Validation</small><b>Attestation prévue</b></div></span></div><Link href={`/inscription?formation=${course.slug}`} className="button primary">Demander une inscription <ArrowRight/></Link><small className="info-note">Notre équipe vous recontacte pour confirmer les dates et modalités.</small></aside></div></section>
  <section className="course-bottom-cta"><div className="container"><div><span>Une question sur ce parcours ?</span><h2>Parlons de votre projet de formation.</h2></div><div><Link href={`/inscription?formation=${course.slug}`} className="button gold-button">S&apos;inscrire <ArrowRight/></Link><Link href="/contact" className="button outline-light">Nous contacter</Link></div></div></section>
</main><Footer/><WhatsApp course={course.title}/></>}
