export type IsoStandard = "iso9001" | "iso14001" | "iso45001";

export type IsoSector = {
  slug: string;
  name: string;
  group: "Santé" | "Éducation" | "BTP & ingénierie" | "Industrie" | "Transport & logistique" | "Services";
  summary: string;
  challenges: string[];
  benefits: Record<IsoStandard, string[]>;
  actions: string[];
};

export const isoSlides = [
  {
    eyebrow: "Santé",
    title: "Fiabiliser chaque étape du parcours patient",
    text: "Procédures maîtrisées, traçabilité des dossiers, gestion des risques et amélioration continue au service de la qualité des soins.",
    image: "/photos/iso-health.jpg",
    alt: "Professionnel de santé utilisant un outil numérique",
    sectors: "Cabinets, cliniques, laboratoires et centres de radiologie",
    benefits: ["Parcours patient maîtrisé", "Traçabilité renforcée", "Risques mieux prévenus"],
    sectorSlug: "cabinet-medical",
  },
  {
    eyebrow: "BTP",
    title: "Transformer les exigences QHSE en réflexes chantier",
    text: "Responsabilités claires, contrôles documentés et prévention opérationnelle pour mieux tenir la qualité, les délais et la sécurité.",
    image: "/photos/trainings/iso-45001.webp",
    alt: "Professionnel du BTP équipé sur un chantier",
    sectors: "Entreprises de construction et bureaux d’études",
    benefits: ["Contrôles chantier tracés", "Nuisances réduites", "Prévention renforcée"],
    sectorSlug: "societe-btp",
  },
  {
    eyebrow: "Industrie",
    title: "Stabiliser la production et réduire les risques",
    text: "Des processus mesurés, des incidents analysés et des standards de travail compris par les équipes, de l’atelier à la direction.",
    image: "/photos/services/iso-45001.webp",
    alt: "Opérateur industriel réalisant une opération de production",
    sectors: "Industrie manufacturière, agroalimentaire et maintenance",
    benefits: ["Procédés plus stables", "Impacts mesurés", "Travail plus sûr"],
    sectorSlug: "industrie-manufacturiere",
  },
  {
    eyebrow: "Formation",
    title: "Structurer une expérience pédagogique cohérente",
    text: "Conception, réalisation et évaluation des formations intégrées dans un système qui écoute les apprenants et améliore les résultats.",
    image: "/photos/formation.jpg",
    alt: "Session de formation professionnelle en entreprise",
    sectors: "Centres de formation, écoles et universités privées",
    benefits: ["Programmes harmonisés", "Évaluations utiles", "Amélioration continue"],
    sectorSlug: "centre-formation",
  },
  {
    eyebrow: "Transport & logistique",
    title: "Maîtriser les flux, les délais et la sécurité",
    text: "Indicateurs de service, maintenance planifiée, analyse des incidents et maîtrise des impacts pour des opérations plus fiables.",
    image: "/photos/iso-logistics.jpg",
    alt: "Chariot élévateur devant un bâtiment logistique",
    sectors: "Transporteurs, plateformes logistiques et multiservices",
    benefits: ["Flux mieux maîtrisés", "Moins d’erreurs", "Sécurité opérationnelle"],
    sectorSlug: "societe-logistique",
  },
] as const;

type SectorInput = Pick<IsoSector, "slug" | "name" | "group" | "summary" | "challenges" | "actions"> & {
  quality: string;
  environment: string;
  safety: string;
};

function sector(input: SectorInput): IsoSector {
  return {
    ...input,
    benefits: {
      iso9001: [
        input.quality,
        "Clarifier les responsabilités et mesurer la satisfaction des clients.",
        "Traiter les écarts avec des actions correctives suivies et vérifiables.",
      ],
      iso14001: [
        input.environment,
        "Identifier les obligations applicables et suivre les consommations utiles.",
        "Prévenir la pollution et réduire progressivement les impacts significatifs.",
      ],
      iso45001: [
        input.safety,
        "Associer les équipes à l’identification des dangers et aux décisions de prévention.",
        "Analyser les incidents pour éviter leur répétition et renforcer la culture sécurité.",
      ],
    },
  };
}

export const isoSectors: IsoSector[] = [
  sector({
    slug: "cabinet-medical",
    name: "Cabinet médical",
    group: "Santé",
    summary: "Organiser le parcours du patient, sécuriser les informations et rendre les pratiques du cabinet plus régulières.",
    challenges: ["Dossiers patients incomplets ou difficiles à retrouver", "Délais d’attente et rendez-vous peu mesurés", "Gestion informelle des réclamations et événements indésirables"],
    quality: "Formaliser l’accueil, la consultation, le suivi et la gestion des réclamations.",
    environment: "Mieux gérer les déchets de soins, les consommables et l’énergie du cabinet.",
    safety: "Prévenir les expositions biologiques, les troubles ergonomiques et les situations d’urgence.",
    actions: ["Cartographier le parcours patient et les points de contrôle", "Créer des check-lists simples pour les dossiers et équipements", "Suivre quelques indicateurs : attente, réclamations, incidents et actions"],
  }),
  sector({
    slug: "clinique-privee",
    name: "Clinique privée",
    group: "Santé",
    summary: "Coordonner les services médicaux, administratifs et techniques autour d’un système de management commun.",
    challenges: ["Nombreuses interfaces entre admission, soins, pharmacie et facturation", "Exigences fortes de traçabilité et de continuité", "Risques multiples pour les patients, les équipes et les prestataires"],
    quality: "Standardiser les interfaces entre services et sécuriser la continuité du parcours patient.",
    environment: "Maîtriser déchets médicaux, effluents, énergie et achats sensibles.",
    safety: "Structurer la prévention des risques biologiques, chimiques, techniques et psychosociaux.",
    actions: ["Définir les pilotes de processus et leurs objectifs", "Revoir les circuits critiques et les plans d’urgence", "Installer un comité de pilotage avec indicateurs qualité, environnement et sécurité"],
  }),
  sector({
    slug: "laboratoire-analyses",
    name: "Laboratoire d’analyses",
    group: "Santé",
    summary: "Sécuriser la chaîne pré-analytique, analytique et post-analytique et assurer une traçabilité complète.",
    challenges: ["Erreurs possibles d’identification ou de prélèvement", "Équipements et réactifs à surveiller en continu", "Déchets biologiques et chimiques à maîtriser"],
    quality: "Fiabiliser l’identification, les contrôles, la validation et la transmission des résultats.",
    environment: "Réduire les pertes de réactifs et sécuriser le tri des déchets biologiques et chimiques.",
    safety: "Maîtriser les expositions, les équipements de protection et les conduites à tenir après incident.",
    actions: ["Décrire la chaîne de traçabilité de l’échantillon", "Planifier étalonnages, maintenances et contrôles qualité", "Analyser erreurs, non-conformités et presque-accidents"],
  }),
  sector({
    slug: "centre-radiologie",
    name: "Centre de radiologie",
    group: "Santé",
    summary: "Fiabiliser la prise en charge, la disponibilité des équipements et la maîtrise des risques spécifiques.",
    challenges: ["Coordination complexe entre prescription, examen et compte rendu", "Disponibilité et maintenance d’équipements critiques", "Radioprotection, confidentialité et préparation aux urgences"],
    quality: "Maîtriser la programmation, l’identitovigilance, les comptes rendus et la satisfaction patient.",
    environment: "Suivre énergie, consommables et déchets liés aux activités d’imagerie.",
    safety: "Renforcer radioprotection, ergonomie, habilitations et réponse aux situations d’urgence.",
    actions: ["Cartographier le parcours d’examen et les contrôles associés", "Formaliser maintenance, disponibilité et gestion des pannes", "Suivre délais de rendez-vous, reprises, incidents et réclamations"],
  }),
  sector({
    slug: "centre-formation",
    name: "Centre de formation",
    group: "Éducation",
    summary: "Piloter les formations depuis l’analyse du besoin jusqu’à l’évaluation de leur efficacité.",
    challenges: ["Besoins clients mal traduits en objectifs pédagogiques", "Qualité variable selon les formateurs et les sessions", "Évaluations limitées à la satisfaction immédiate"],
    quality: "Structurer conception, animation, évaluation et amélioration des programmes.",
    environment: "Réduire papier, déplacements inutiles et consommations des locaux.",
    safety: "Sécuriser les salles, les équipements pédagogiques et les déplacements des participants.",
    actions: ["Créer une fiche de cadrage par action de formation", "Qualifier les formateurs et harmoniser les supports", "Mesurer satisfaction, acquis et transfert en situation de travail"],
  }),
  sector({
    slug: "ecole-privee",
    name: "École privée",
    group: "Éducation",
    summary: "Mettre les familles, les élèves et les équipes au cœur d’une organisation scolaire maîtrisée.",
    challenges: ["Multiples attentes des élèves, familles et autorités", "Processus d’inscription, d’enseignement et de suivi parfois dispersés", "Sécurité des personnes et gestion des situations sensibles"],
    quality: "Harmoniser les processus scolaires et mieux écouter élèves, familles et personnels.",
    environment: "Agir sur déchets, eau, énergie et sensibilisation des élèves.",
    safety: "Évaluer les risques des locaux, transports, activités et situations d’urgence.",
    actions: ["Cartographier inscription, scolarité, évaluation et communication", "Mettre en place un registre d’incidents et réclamations", "Définir des objectifs annuels suivis en revue de direction"],
  }),
  sector({
    slug: "universite-privee",
    name: "Université privée",
    group: "Éducation",
    summary: "Coordonner programmes, services aux étudiants, partenariats et amélioration continue à grande échelle.",
    challenges: ["Processus académiques et administratifs fortement interconnectés", "Expérience étudiante difficile à mesurer de bout en bout", "Gestion de nombreux campus, laboratoires ou prestataires"],
    quality: "Piloter l’offre académique, les services et l’expérience étudiante avec des indicateurs cohérents.",
    environment: "Maîtriser les impacts des campus, laboratoires, achats et déplacements.",
    safety: "Organiser la prévention sur les campus et la gestion coordonnée des urgences.",
    actions: ["Définir la gouvernance et les pilotes des processus clés", "Construire un tableau de bord académique et support", "Programmer audits internes et revues d’amélioration par périmètre"],
  }),
  sector({
    slug: "societe-btp",
    name: "Société BTP",
    group: "BTP & ingénierie",
    summary: "Relier préparation, exécution et contrôle chantier pour tenir les exigences client et prévenir les accidents.",
    challenges: ["Variabilité des chantiers, équipes et sous-traitants", "Contrôles qualité parfois tardifs ou peu tracés", "Coactivité, hauteur, engins et autres risques majeurs"],
    quality: "Maîtriser plans, matériaux, contrôles, réserves et réception des travaux.",
    environment: "Réduire nuisances, déchets, poussières et consommations sur chantier.",
    safety: "Planifier la prévention, contrôler les sous-traitants et sécuriser les activités à haut risque.",
    actions: ["Préparer un plan qualité et sécurité adapté à chaque chantier", "Déployer causeries, inspections et fiches de contrôle", "Suivre réserves, incidents, déchets et actions jusqu’à clôture"],
  }),
  sector({
    slug: "bureau-etudes",
    name: "Bureau d’études",
    group: "BTP & ingénierie",
    summary: "Sécuriser les données d’entrée, les revues techniques et la maîtrise des versions livrées au client.",
    challenges: ["Évolutions fréquentes des besoins et documents", "Risques d’erreur aux interfaces entre disciplines", "Charge de travail, ergonomie et déplacements terrain"],
    quality: "Structurer revues de conception, vérifications, validations et gestion des modifications.",
    environment: "Intégrer des critères environnementaux dans les études et les choix techniques.",
    safety: "Prévenir les risques liés au travail sur écran, aux visites terrain et à la pression des délais.",
    actions: ["Formaliser la revue des données d’entrée et des livrables", "Mettre en place une gestion claire des versions et validations", "Mesurer retours client, reprises d’études et respect des délais"],
  }),
  sector({
    slug: "industrie-manufacturiere",
    name: "Industrie manufacturière",
    group: "Industrie",
    summary: "Rendre les procédés stables, les contrôles fiables et les améliorations visibles dans l’atelier.",
    challenges: ["Variations de qualité, rebuts et arrêts non planifiés", "Instructions de travail parfois éloignées de la pratique", "Machines, énergies et produits générant des risques significatifs"],
    quality: "Stabiliser les procédés, réduire les défauts et renforcer la traçabilité de production.",
    environment: "Piloter déchets, énergie, émissions et utilisation des matières.",
    safety: "Maîtriser machines, consignations, manutention et exposition aux produits.",
    actions: ["Identifier paramètres critiques, contrôles et compétences nécessaires", "Mettre à jour standards visuels et plans de maintenance", "Animer quotidiennement qualité, performance et sécurité avec quelques KPI"],
  }),
  sector({
    slug: "industrie-agroalimentaire",
    name: "Industrie agroalimentaire",
    group: "Industrie",
    summary: "Renforcer la maîtrise des procédés, la traçabilité et les conditions de travail dans un environnement exigeant.",
    challenges: ["Variabilité des matières, exigences d’hygiène et délais courts", "Consommations élevées d’eau, énergie et emballages", "Risques liés au froid, aux machines, au nettoyage et aux produits"],
    quality: "Améliorer la régularité des procédés, la traçabilité et le traitement des réclamations.",
    environment: "Réduire pertes matières, effluents, énergie et déchets d’emballage.",
    safety: "Prévenir coupures, glissades, manutentions, expositions et risques machines.",
    actions: ["Relier exigences clients, contrôles et dossiers de lot", "Suivre rendements, pertes, consommations et non-conformités", "Coordonner ISO avec les dispositifs de sécurité alimentaire déjà en place"],
  }),
  sector({
    slug: "maintenance-industrielle",
    name: "Maintenance industrielle",
    group: "Industrie",
    summary: "Planifier les interventions, fiabiliser les équipements et sécuriser le travail dans des environnements variables.",
    challenges: ["Interventions urgentes et informations techniques dispersées", "Pièces, sous-traitants et historiques difficiles à maîtriser", "Consignation, coactivité et travaux à risques"],
    quality: "Structurer demandes, préparation, exécution et retour d’expérience des interventions.",
    environment: "Maîtriser huiles, déchets techniques, fuites et consommations liées aux équipements.",
    safety: "Sécuriser consignations, permis de travail, habilitations et interventions des prestataires.",
    actions: ["Prioriser préventif, correctif et criticité des équipements", "Standardiser bons de travail et comptes rendus", "Auditer les interventions à risque et analyser les pannes récurrentes"],
  }),
  sector({
    slug: "societe-transport",
    name: "Société de transport",
    group: "Transport & logistique",
    summary: "Fiabiliser les tournées, les véhicules et l’information client tout en maîtrisant les risques routiers.",
    challenges: ["Retards, aléas et communication client en temps réel", "Maintenance de flotte et suivi documentaire", "Risque routier, fatigue et consommation de carburant"],
    quality: "Piloter ponctualité, intégrité des livraisons, réclamations et performance des tournées.",
    environment: "Réduire carburant, émissions, trajets à vide et déchets de maintenance.",
    safety: "Prévenir le risque routier, la fatigue, les manutentions et les situations d’urgence.",
    actions: ["Définir les indicateurs service, flotte et sécurité", "Planifier contrôles réglementaires et maintenance préventive", "Analyser retards, incidents et consommation par trajet ou véhicule"],
  }),
  sector({
    slug: "societe-logistique",
    name: "Société logistique",
    group: "Transport & logistique",
    summary: "Maîtriser réception, stockage, préparation et expédition avec des flux visibles et sûrs.",
    challenges: ["Erreurs de stock ou de préparation", "Pics d’activité, multiplicité des clients et exigences variables", "Circulation d’engins, manutention et organisation des zones"],
    quality: "Réduire erreurs, avaries et délais grâce à des contrôles intégrés aux flux.",
    environment: "Agir sur emballages, énergie, déchets et optimisation des transports.",
    safety: "Séparer les flux, sécuriser engins et prévenir chutes, heurts et manutentions pénibles.",
    actions: ["Cartographier les flux physiques et informatiques", "Définir contrôles aux étapes critiques et règles de stockage", "Suivre erreurs, productivité, incidents, énergie et déchets"],
  }),
  sector({
    slug: "hotel",
    name: "Hôtel",
    group: "Services",
    summary: "Créer une expérience client régulière tout en maîtrisant les opérations, ressources et risques de l’établissement.",
    challenges: ["Expérience dépendante de nombreux services et prestataires", "Forte consommation d’eau, d’énergie et de produits", "Risques clients et salariés dans un fonctionnement continu"],
    quality: "Harmoniser réservation, accueil, hébergement, restauration et traitement des retours.",
    environment: "Réduire eau, énergie, déchets alimentaires et produits à impact.",
    safety: "Maîtriser incendie, piscines, cuisines, maintenance, ergonomie et travail isolé.",
    actions: ["Décrire les parcours client et les standards de service", "Installer des indicateurs satisfaction, ressources et sécurité", "Intégrer prestataires, saisonniers et urgences dans les procédures"],
  }),
  sector({
    slug: "restaurant",
    name: "Restaurant",
    group: "Services",
    summary: "Rendre le service plus régulier, réduire les pertes et mieux prévenir les risques en cuisine et en salle.",
    challenges: ["Variabilité du service et gestion des heures de pointe", "Gaspillage alimentaire, emballages et consommation d’énergie", "Chaleur, coupures, glissades et manutentions"],
    quality: "Structurer achats, préparation, service, retour client et traitement des écarts.",
    environment: "Réduire gaspillage, huiles usagées, emballages, eau et énergie.",
    safety: "Prévenir brûlures, coupures, glissades, incendie et contraintes ergonomiques.",
    actions: ["Créer des standards simples pour les étapes critiques", "Mesurer retours clients, pertes et consommations", "Former les équipes aux gestes sûrs et aux conduites d’urgence"],
  }),
  sector({
    slug: "societe-nettoyage",
    name: "Société de nettoyage",
    group: "Services",
    summary: "Garantir un niveau de service vérifiable sur chaque site et sécuriser les produits et méthodes utilisés.",
    challenges: ["Qualité de prestation variable entre sites et équipes", "Gestion des produits, dosages, stocks et déchets", "Exposition chimique, gestes répétitifs et travail isolé"],
    quality: "Définir les niveaux de service, contrôles et preuves de réalisation par site.",
    environment: "Choisir et doser les produits, limiter l’eau et maîtriser les déchets.",
    safety: "Évaluer risques chimiques, ergonomiques, électriques et liés au travail isolé.",
    actions: ["Créer un plan de nettoyage et de contrôle par contrat", "Former et habiliter les équipes selon les risques du site", "Suivre réclamations, contrôles, consommations et incidents"],
  }),
  sector({
    slug: "societe-gardiennage",
    name: "Société de gardiennage",
    group: "Services",
    summary: "Fiabiliser les consignes, les prises de poste et la remontée d’incidents sur des sites multiples.",
    challenges: ["Consignes différentes selon chaque client et chaque poste", "Traçabilité des rondes et événements", "Travail de nuit, isolement, tensions et situations d’urgence"],
    quality: "Standardiser la prise de poste, les rondes, les rapports et le traitement des incidents.",
    environment: "Maîtriser les consommations des postes, déplacements et déchets courants.",
    safety: "Prévenir travail isolé, agressions, fatigue et exposition aux risques du site client.",
    actions: ["Formaliser les consignes et critères de contrôle par site", "Vérifier compétences, équipements et passations", "Analyser incidents, écarts de ronde et retours client"],
  }),
  sector({
    slug: "cabinet-comptable",
    name: "Cabinet comptable",
    group: "Services",
    summary: "Sécuriser la collecte, la production et la restitution des dossiers dans un environnement à fortes échéances.",
    challenges: ["Pièces reçues tardivement ou sous des formats multiples", "Risque d’erreur lors des périodes de forte charge", "Confidentialité, continuité informatique et pression temporelle"],
    quality: "Standardiser collecte, revue, validation et communication sur les dossiers.",
    environment: "Réduire papier, stockage physique et déplacements grâce à des flux numériques maîtrisés.",
    safety: "Agir sur ergonomie, charge de travail et prévention des risques psychosociaux.",
    actions: ["Définir check-lists et niveaux de revue par prestation", "Suivre dossiers bloqués, délais, corrections et satisfaction", "Préparer continuité d’activité et règles de sécurité documentaire"],
  }),
  sector({
    slug: "cabinet-conseil",
    name: "Cabinet de conseil",
    group: "Services",
    summary: "Maîtriser le cadrage, la réalisation et la capitalisation des missions sans rigidifier l’expertise.",
    challenges: ["Attentes client parfois implicites ou évolutives", "Qualité dépendante des méthodes de chaque consultant", "Capitalisation et mesure des résultats limitées"],
    quality: "Sécuriser proposition, cadrage, livrables, validation et retour d’expérience.",
    environment: "Réduire déplacements, impressions et impacts des événements professionnels.",
    safety: "Prévenir fatigue, déplacements, travail isolé et surcharge de missions.",
    actions: ["Standardiser les jalons et critères d’acceptation", "Organiser relecture, gestion des versions et capitalisation", "Mesurer satisfaction, respect des engagements et efficacité des actions"],
  }),
  sector({
    slug: "societe-informatique",
    name: "Société informatique",
    group: "Services",
    summary: "Rendre les engagements de service, les changements et la résolution des incidents plus prévisibles.",
    challenges: ["Priorités changeantes et exigences parfois incomplètes", "Incidents, versions et connaissances à tracer", "Obsolescence, consommation numérique et charge mentale"],
    quality: "Maîtriser besoins, développement, tests, changements, incidents et niveaux de service.",
    environment: "Agir sur durée de vie du matériel, déchets électroniques, énergie et sobriété numérique.",
    safety: "Prévenir sédentarité, ergonomie, hyperconnexion et risques psychosociaux.",
    actions: ["Définir les flux demande-changement-livraison-support", "Clarifier responsabilités, critères de test et escalades", "Suivre qualité de service, incidents récurrents et actions d’amélioration"],
  }),
  sector({
    slug: "commerce-distribution",
    name: "Commerce et distribution",
    group: "Services",
    summary: "Relier approvisionnement, stock, vente et service client pour mieux maîtriser disponibilité et expérience d’achat.",
    challenges: ["Ruptures, surstocks et écarts d’inventaire", "Qualité de service variable entre points de vente", "Déchets, manutention, circulation et sécurité du public"],
    quality: "Améliorer disponibilité, traçabilité, accueil et traitement des retours clients.",
    environment: "Réduire emballages, invendus, énergie et déchets de l’activité.",
    safety: "Maîtriser manutention, chutes, circulation, incendie et situations avec le public.",
    actions: ["Cartographier approvisionnement, réception, vente et retour", "Définir contrôles de stock et standards d’accueil", "Piloter ruptures, réclamations, pertes, énergie et incidents"],
  }),
  sector({
    slug: "entreprise-multiservices",
    name: "Entreprise multiservices",
    group: "Services",
    summary: "Construire un système commun tout en adaptant les méthodes aux exigences de chaque activité et client.",
    challenges: ["Contrats, métiers, sites et risques très différents", "Responsabilités et preuves de prestation parfois dispersées", "Sous-traitance et compétences difficiles à piloter globalement"],
    quality: "Créer un socle commun pour les contrats, contrôles, réclamations et revues de performance.",
    environment: "Évaluer les impacts par métier et harmoniser les pratiques prioritaires.",
    safety: "Définir un cadre commun de prévention puis l’adapter aux risques de chaque site.",
    actions: ["Structurer une cartographie commune et des annexes par activité", "Centraliser compétences, équipements, contrôles et incidents", "Piloter les contrats avec un tableau de bord QHSE consolidé"],
  }),
];

export const sectorGroups = [...new Set(isoSectors.map((item) => item.group))];
