import { whatsappMessages } from "@/app/_lib/site";

export type LinkItem = { label: string; href: string };
export type FaqItem = { question: string; answer: string };

export type ServicePageData = {
  path: string;
  eyebrow: string;
  title: string;
  description: string;
  image: string;
  imageAlt: string;
  problems: string[];
  objectives: string[];
  steps: { title: string; text: string }[];
  deliverables: string[];
  benefits: string[];
  audience: string[];
  examples: string[];
  faq: FaqItem[];
  related: LinkItem[];
  children?: LinkItem[];
  primaryLabel: string;
  whatsappMessage: string;
  seoTitle: string;
  seoDescription: string;
};

const sharedSteps = [
  { title: "Cadrer", text: "Clarifier la situation, les priorités, les contraintes et le résultat attendu." },
  { title: "Diagnostiquer", text: "Observer les pratiques, écouter les équipes et objectiver les écarts." },
  { title: "Construire", text: "Définir une feuille de route réaliste, des outils utiles et des responsabilités claires." },
  { title: "Déployer", text: "Mettre en œuvre avec vos équipes, mesurer les progrès et ajuster durablement." },
];

const pages: ServicePageData[] = [
  {
    path: "conseil-accompagnement",
    eyebrow: "Conseil & accompagnement",
    title: "Des décisions plus claires pour faire avancer votre entreprise.",
    description: "LIDA accompagne les dirigeants et les PME marocaines pour transformer une situation complexe en priorités concrètes, pilotables et partagées.",
    image: "/photos/conseil.jpg",
    imageAlt: "Réunion de conseil et accompagnement d’entreprise",
    problems: ["Priorités dispersées", "Décisions difficiles à traduire en actions", "Manque de visibilité sur la performance", "Équipes insuffisamment alignées"],
    objectives: ["Structurer la réflexion du dirigeant", "Choisir les projets à plus fort impact", "Installer un pilotage simple", "Sécuriser l’exécution dans la durée"],
    steps: sharedSteps,
    deliverables: ["Diagnostic de situation", "Feuille de route priorisée", "Plan d’action", "Rituels et indicateurs de suivi"],
    benefits: ["Décisions objectivées", "Priorités partagées", "Responsabilités lisibles", "Progression mesurable"],
    audience: ["Dirigeants de PME", "Entrepreneurs", "Managers", "Entreprises en phase de structuration ou de transformation"],
    examples: ["Diagnostic global avant une phase de croissance", "Remise à plat des priorités opérationnelles", "Accompagnement d’un comité de direction"],
    faq: [
      { question: "Par quoi commence un accompagnement ?", answer: "Un premier échange permet de cadrer le besoin. LIDA propose ensuite un diagnostic ciblé avant de recommander un plan d’intervention." },
      { question: "L’accompagnement convient-il à une petite entreprise ?", answer: "Oui. La méthode, le rythme et les livrables sont adaptés à la taille, aux ressources et à la maturité de chaque entreprise." },
      { question: "Intervenez-vous uniquement à Marrakech ?", answer: "Les missions peuvent être organisées sur site au Maroc, à distance ou dans un format hybride selon le besoin." },
    ],
    related: [{ label: "Structurer l’organisation", href: "/gestion-organisation" }, { label: "Digitaliser les opérations", href: "/digitalisation" }],
    children: [
      { label: "Diagnostic d’entreprise", href: "/conseil-accompagnement/diagnostic-entreprise" },
      { label: "Optimisation de la performance", href: "/conseil-accompagnement/optimisation-performance" },
      { label: "Accompagnement managérial", href: "/conseil-accompagnement/accompagnement-managerial" },
    ],
    primaryLabel: "Demander un diagnostic",
    whatsappMessage: whatsappMessages.diagnostic,
    seoTitle: "Cabinet de conseil et accompagnement au Maroc",
    seoDescription: "Conseil aux PME au Maroc : diagnostic, feuille de route, accompagnement du dirigeant et pilotage de la performance avec LIDA.",
  },
  {
    path: "conseil-accompagnement/diagnostic-entreprise",
    eyebrow: "Conseil · Diagnostic",
    title: "Obtenir une lecture objective de votre entreprise avant d’agir.",
    description: "Le diagnostic LIDA met en évidence les points de blocage, les risques et les leviers d’amélioration afin de concentrer les efforts là où ils créent réellement de la valeur.",
    image: "/photos/conseil.jpg",
    imageAlt: "Analyse structurée de la situation d’une entreprise",
    problems: ["Difficulté à identifier la cause des dysfonctionnements", "Décisions fondées sur des impressions", "Multiplication des urgences", "Projets lancés sans ordre de priorité"],
    objectives: ["Établir un état des lieux fiable", "Distinguer causes et symptômes", "Hiérarchiser les risques et opportunités", "Définir les premières actions utiles"],
    steps: [{ title: "Entretien de cadrage", text: "Compréhension des enjeux du dirigeant et du périmètre à examiner." }, { title: "Collecte terrain", text: "Entretiens, observation des processus et revue des documents disponibles." }, { title: "Analyse", text: "Qualification des écarts, de leurs impacts et de leur niveau de priorité." }, { title: "Restitution", text: "Présentation des constats, arbitrages et feuille de route initiale." }],
    deliverables: ["Rapport de diagnostic", "Cartographie des enjeux", "Matrice de priorités", "Plan d’action 30/60/90 jours"],
    benefits: ["Vision factuelle", "Risques mieux maîtrisés", "Décisions accélérées", "Investissements mieux ciblés"],
    audience: ["Dirigeants", "Entreprises en croissance", "PME confrontées à des dysfonctionnements récurrents", "Organisations préparant une transformation"],
    examples: ["Diagnostic organisationnel d’une PME", "Évaluation des pratiques de pilotage", "Revue des flux administratifs et opérationnels"],
    faq: [{ question: "Combien de temps dure un diagnostic ?", answer: "La durée dépend du périmètre et du nombre d’interlocuteurs. Elle est précisée après le cadrage initial." }, { question: "Faut-il préparer des documents ?", answer: "LIDA fournit une liste ciblée. Les documents existants suffisent : l’objectif est d’évaluer la réalité, pas de créer des preuves artificielles." }, { question: "Le diagnostic oblige-t-il à poursuivre la mission ?", answer: "Non. Vous disposez d’une restitution exploitable et restez libre de la suite à donner." }],
    related: [{ label: "Optimiser la performance", href: "/conseil-accompagnement/optimisation-performance" }, { label: "Organisation & processus", href: "/gestion-organisation/organisation-processus" }],
    primaryLabel: "Planifier un diagnostic",
    whatsappMessage: whatsappMessages.diagnostic,
    seoTitle: "Diagnostic d’entreprise au Maroc",
    seoDescription: "Diagnostic stratégique et opérationnel pour PME : état des lieux, priorités, risques et plan d’action concret.",
  },
  {
    path: "conseil-accompagnement/optimisation-performance",
    eyebrow: "Conseil · Performance",
    title: "Transformer vos objectifs en performance pilotée.",
    description: "LIDA aide votre entreprise à choisir les bons indicateurs, réduire les irritants et installer une dynamique d’amélioration concrète.",
    image: "/photos/conseil.jpg",
    imageAlt: "Pilotage et optimisation de la performance",
    problems: ["Objectifs non mesurés", "Indicateurs trop nombreux ou peu utiles", "Écarts découverts tardivement", "Actions d’amélioration sans suivi"],
    objectives: ["Relier stratégie et opérations", "Définir des KPI compréhensibles", "Réduire les pertes de temps et les reprises", "Installer des revues de performance"],
    steps: sharedSteps,
    deliverables: ["Arbre d’objectifs", "Tableau de bord", "Plan d’amélioration", "Trame de revue de performance"],
    benefits: ["Pilotage réactif", "Équipes responsabilisées", "Écarts visibles", "Amélioration continue structurée"],
    audience: ["Directions générales", "Responsables opérationnels", "Responsables qualité", "PME souhaitant professionnaliser leur pilotage"],
    examples: ["Création d’un tableau de bord de direction", "Optimisation d’un processus critique", "Mise en place de revues mensuelles"],
    faq: [{ question: "Combien d’indicateurs faut-il suivre ?", answer: "Seulement ceux qui permettent une décision ou une action. LIDA privilégie un nombre limité de KPI fiables et compris." }, { question: "Pouvez-vous exploiter nos outils actuels ?", answer: "Oui. La priorité est d’améliorer le pilotage avec l’existant avant de recommander un nouvel outil." }, { question: "Comment mobiliser les équipes ?", answer: "Les indicateurs et routines sont construits avec les personnes concernées afin de favoriser leur appropriation." }],
    related: [{ label: "Tableaux de bord", href: "/digitalisation/tableaux-de-bord" }, { label: "Pilotage de la performance", href: "/gestion-organisation/pilotage-performance" }],
    primaryLabel: "Évaluer ma performance",
    whatsappMessage: whatsappMessages.diagnostic,
    seoTitle: "Optimisation de la performance d’entreprise",
    seoDescription: "KPI, tableaux de bord et plans d’amélioration pour piloter la performance de votre PME au Maroc.",
  },
  {
    path: "conseil-accompagnement/accompagnement-managerial",
    eyebrow: "Conseil · Management",
    title: "Donner aux managers les repères pour décider et faire agir.",
    description: "Un accompagnement concret pour clarifier les rôles, structurer les routines et renforcer la capacité des managers à conduire les priorités avec leurs équipes.",
    image: "/photos/conseil.jpg",
    imageAlt: "Accompagnement managérial d’une équipe",
    problems: ["Managers pris dans l’opérationnel", "Responsabilités ambiguës", "Réunions longues et peu décisionnelles", "Difficulté à accompagner le changement"],
    objectives: ["Clarifier le rôle managérial", "Améliorer la communication et la délégation", "Structurer les rituels d’équipe", "Piloter les engagements"],
    steps: [{ title: "Cadrage", text: "Identification des situations managériales prioritaires." }, { title: "Observation", text: "Analyse des pratiques, réunions et interfaces clés." }, { title: "Co-construction", text: "Création de repères, outils et routines adaptés." }, { title: "Accompagnement", text: "Mises en situation, retours d’expérience et ajustements." }],
    deliverables: ["Matrice des responsabilités", "Rituels managériaux", "Supports de suivi", "Plan de progrès individuel ou collectif"],
    benefits: ["Décisions plus rapides", "Délégation plus sûre", "Réunions utiles", "Équipes mieux alignées"],
    audience: ["Dirigeants", "Managers de proximité", "Responsables de service", "Managers nouvellement nommés"],
    examples: ["Structuration d’un comité de pilotage", "Clarification des rôles d’une équipe", "Accompagnement d’une prise de fonction"],
    faq: [{ question: "S’agit-il de coaching individuel ?", answer: "L’intervention peut combiner accompagnement individuel, ateliers collectifs et amélioration des pratiques de management." }, { question: "Peut-on cibler une difficulté précise ?", answer: "Oui. Le format est construit autour de situations réelles : délégation, réunions, arbitrage ou pilotage d’équipe." }, { question: "Les échanges sont-ils confidentiels ?", answer: "Le cadre de confidentialité et les règles de restitution sont définis explicitement au démarrage." }],
    related: [{ label: "Formation Management", href: "/formation/management" }, { label: "Organisation des rôles", href: "/gestion-organisation/organisation-processus" }],
    primaryLabel: "Échanger sur votre besoin",
    whatsappMessage: whatsappMessages.diagnostic,
    seoTitle: "Accompagnement managérial au Maroc",
    seoDescription: "Accompagnement des dirigeants et managers : rôles, délégation, routines d’équipe et conduite des priorités.",
  },
  {
    path: "digitalisation",
    eyebrow: "Digitalisation",
    title: "Digitaliser ce qui ralentit réellement votre activité.",
    description: "LIDA simplifie vos processus avant de choisir les outils, pour réduire les tâches manuelles, fiabiliser l’information et améliorer les décisions.",
    image: "/photos/digitalisation.jpg",
    imageAlt: "Digitalisation des processus d’une PME",
    problems: ["Saisies multiples", "Fichiers dispersés", "Reporting chronophage", "Informations difficiles à consolider"],
    objectives: ["Fluidifier les processus", "Centraliser les données utiles", "Automatiser les tâches répétitives", "Donner une vision à jour de l’activité"],
    steps: sharedSteps,
    deliverables: ["Cartographie des flux", "Cahier des besoins", "Workflows digitalisés", "Tableaux de bord et guides utilisateurs"],
    benefits: ["Temps administratif réduit", "Moins d’erreurs", "Données plus fiables", "Décisions mieux informées"],
    audience: ["PME", "Services administratifs", "Directions financières", "Équipes opérationnelles"],
    examples: ["Circuit de validation digital", "Centralisation du suivi client", "Reporting automatique de direction"],
    faq: [{ question: "Faut-il changer tous nos outils ?", answer: "Non. LIDA évalue d’abord les outils et fichiers existants afin de réutiliser ce qui fonctionne." }, { question: "La digitalisation convient-elle à une petite structure ?", answer: "Oui, à condition de cibler les irritants prioritaires et de déployer des solutions proportionnées." }, { question: "Accompagnez-vous la prise en main ?", answer: "Oui. Documentation, formation et période d’ajustement font partie de l’approche proposée." }],
    related: [{ label: "Organisation des processus", href: "/gestion-organisation/organisation-processus" }, { label: "Formation IA pour la gestion", href: "/formation/gestion-intelligence-artificielle" }],
    children: [{ label: "Digitalisation des processus", href: "/digitalisation/digitalisation-processus" }, { label: "Tableaux de bord", href: "/digitalisation/tableaux-de-bord" }, { label: "Outils de gestion", href: "/digitalisation/outils-gestion" }],
    primaryLabel: "Demander un diagnostic digital",
    whatsappMessage: whatsappMessages.digitalisation,
    seoTitle: "Digitalisation des PME au Maroc",
    seoDescription: "Digitalisation des processus, automatisation, données et tableaux de bord pour les PME marocaines.",
  },
  {
    path: "digitalisation/digitalisation-processus",
    eyebrow: "Digitalisation · Processus",
    title: "Passer de circuits manuels à des workflows simples et fiables.",
    description: "LIDA repense le flux de travail avant de le digitaliser pour éviter d’automatiser les lenteurs, doublons et validations inutiles.",
    image: "/photos/digitalisation.jpg",
    imageAlt: "Workflow et digitalisation de processus",
    problems: ["Documents transmis par plusieurs canaux", "Validations difficiles à suivre", "Informations ressaisies", "Délais dépendants de relances manuelles"],
    objectives: ["Simplifier les étapes", "Tracer les validations", "Réduire la ressaisie", "Sécuriser le partage d’information"],
    steps: sharedSteps,
    deliverables: ["Cartographie avant/après", "Workflow cible", "Paramétrage ou prototype", "Guide de fonctionnement"],
    benefits: ["Délais réduits", "Traçabilité", "Moins d’oublis", "Meilleure coordination"],
    audience: ["Administration", "Achats", "Commercial", "Opérations", "QHSE"],
    examples: ["Demande d’achat et validation", "Suivi d’actions QHSE", "Onboarding d’un collaborateur"],
    faq: [{ question: "Quels processus digitaliser en premier ?", answer: "Ceux qui combinent fréquence élevée, temps perdu, risque d’erreur et impact opérationnel." }, { question: "Peut-on démarrer par un pilote ?", answer: "Oui. Un périmètre pilote permet de valider les usages avant un déploiement plus large." }, { question: "Comment éviter le rejet de l’outil ?", answer: "Les utilisateurs participent à la conception et testent le workflow avant sa généralisation." }],
    related: [{ label: "Outils de gestion", href: "/digitalisation/outils-gestion" }, { label: "Formation IA", href: "/formation/gestion-intelligence-artificielle" }],
    primaryLabel: "Étudier un processus",
    whatsappMessage: whatsappMessages.digitalisation,
    seoTitle: "Digitalisation des processus au Maroc",
    seoDescription: "Simplification et digitalisation des processus métiers pour réduire les tâches manuelles et fiabiliser les validations.",
  },
  {
    path: "digitalisation/tableaux-de-bord",
    eyebrow: "Digitalisation · Reporting",
    title: "Voir l’essentiel de votre activité au bon moment.",
    description: "Des tableaux de bord conçus à partir des décisions à prendre, avec des données compréhensibles, fiables et faciles à actualiser.",
    image: "/photos/digitalisation.jpg",
    imageAlt: "Tableau de bord de pilotage d’entreprise",
    problems: ["Reporting consolidé tardivement", "Indicateurs contradictoires", "Fichiers difficiles à maintenir", "Absence de vue globale"],
    objectives: ["Définir une source fiable", "Automatiser la consolidation", "Visualiser les écarts", "Faciliter les arbitrages"],
    steps: [{ title: "Décisions", text: "Identification des questions auxquelles le tableau de bord doit répondre." }, { title: "Données", text: "Revue des sources, règles de calcul et responsabilités de mise à jour." }, { title: "Prototype", text: "Conception d’une vue simple puis validation avec les utilisateurs." }, { title: "Déploiement", text: "Automatisation, documentation et accompagnement à l’usage." }],
    deliverables: ["Dictionnaire des KPI", "Modèle de données", "Tableau de bord", "Guide d’analyse"],
    benefits: ["Temps de reporting réduit", "Indicateurs partagés", "Alertes plus rapides", "Réunions mieux préparées"],
    audience: ["Dirigeants", "Finance", "Commercial", "Production", "Responsables qualité et QHSE"],
    examples: ["Dashboard commercial", "Suivi de trésorerie", "Pilotage qualité et actions correctives"],
    faq: [{ question: "Travaillez-vous avec Excel ?", answer: "Oui. Selon les volumes et usages, le bon outil peut être Excel, une solution de BI ou un outil déjà présent." }, { question: "Qui définit les KPI ?", answer: "LIDA les construit avec les responsables concernés et formalise clairement leur calcul et leur fréquence." }, { question: "Peut-on automatiser les mises à jour ?", answer: "Oui lorsque les sources sont accessibles et suffisamment structurées. Le niveau d’automatisation est évalué au diagnostic." }],
    related: [{ label: "Formation Excel", href: "/formation/excel" }, { label: "Pilotage de la performance", href: "/gestion-organisation/pilotage-performance" }],
    primaryLabel: "Parler de mon reporting",
    whatsappMessage: whatsappMessages.digitalisation,
    seoTitle: "Tableaux de bord et reporting au Maroc",
    seoDescription: "Conception de KPI, tableaux de bord et reporting automatisé pour piloter votre PME avec des données fiables.",
  },
  {
    path: "digitalisation/outils-gestion",
    eyebrow: "Digitalisation · Outils",
    title: "Choisir et déployer des outils adaptés à vos usages.",
    description: "LIDA traduit les besoins opérationnels en critères de choix concrets, puis accompagne le paramétrage, la documentation et l’adoption.",
    image: "/photos/digitalisation.jpg",
    imageAlt: "Choix et déploiement d’outils de gestion",
    problems: ["Outils sous-utilisés", "Fonctionnalités mal adaptées", "Multiplication des abonnements", "Adoption insuffisante"],
    objectives: ["Formaliser le besoin réel", "Comparer les options sans biais", "Sécuriser le déploiement", "Mesurer l’adoption"],
    steps: sharedSteps,
    deliverables: ["Cahier des besoins", "Grille de comparaison", "Plan de déploiement", "Documentation utilisateur"],
    benefits: ["Choix rationnel", "Coûts maîtrisés", "Adoption facilitée", "Outils cohérents"],
    audience: ["PME en phase d’équipement", "Services administratifs", "Directions opérationnelles", "Entreprises remplaçant un outil devenu limitant"],
    examples: ["Outil de suivi des demandes", "Base documentaire", "Solution de pilotage commercial"],
    faq: [{ question: "LIDA revend-elle des logiciels ?", answer: "L’accompagnement est centré sur votre besoin et vos critères. Les éventuels partenariats sont signalés avec transparence." }, { question: "Pouvez-vous reprendre un projet déjà démarré ?", answer: "Oui, après une revue du besoin, du paramétrage et des difficultés d’adoption." }, { question: "La formation est-elle incluse ?", answer: "Le plan d’intervention peut inclure des guides, ateliers et sessions de prise en main." }],
    related: [{ label: "Digitaliser un processus", href: "/digitalisation/digitalisation-processus" }, { label: "Excel VBA", href: "/formation/excel-vba" }],
    primaryLabel: "Cadrer mon besoin outil",
    whatsappMessage: whatsappMessages.digitalisation,
    seoTitle: "Outils de gestion pour PME au Maroc",
    seoDescription: "Cadrage, choix et déploiement d’outils de gestion adaptés aux processus et aux équipes de votre PME.",
  },
  {
    path: "gestion-organisation",
    eyebrow: "Gestion & organisation",
    title: "Une organisation lisible, pilotable et moins dépendante de l’urgence.",
    description: "LIDA clarifie les processus, les responsabilités, les documents et les indicateurs qui permettent à l’entreprise de fonctionner avec davantage de maîtrise.",
    image: "/photos/organisation.jpg",
    imageAlt: "Organisation et gestion d’une entreprise",
    problems: ["Rôles mal définis", "Pratiques différentes selon les personnes", "Procédures absentes ou inutilisées", "Pilotage réactif plutôt que préventif"],
    objectives: ["Structurer le fonctionnement", "Clarifier qui décide et qui agit", "Formaliser sans bureaucratiser", "Installer une amélioration continue"],
    steps: sharedSteps,
    deliverables: ["Cartographie des processus", "Organigramme et responsabilités", "Procédures utiles", "KPI et routines de pilotage"],
    benefits: ["Coordination renforcée", "Continuité d’activité", "Intégration facilitée", "Performance mieux maîtrisée"],
    audience: ["PME en croissance", "Entreprises familiales", "Structures multi-activités", "Organisations préparant une certification"],
    examples: ["Refonte d’une organisation interne", "Création d’un système documentaire", "Mise en place d’un pilotage mensuel"],
    faq: [{ question: "Faut-il tout formaliser ?", answer: "Non. LIDA formalise ce qui sécurise les activités, clarifie les interfaces ou facilite la transmission." }, { question: "Les équipes participent-elles ?", answer: "Oui. Leur connaissance du terrain est indispensable pour produire une organisation applicable." }, { question: "Cette démarche prépare-t-elle à l’ISO ?", answer: "Elle constitue une base utile, mais un projet ISO comprend des exigences et étapes complémentaires." }],
    related: [{ label: "Digitaliser les processus", href: "/digitalisation" }, { label: "Accompagnement ISO 9001", href: "/accompagnement-iso/iso-9001" }],
    children: [{ label: "Organisation des processus", href: "/gestion-organisation/organisation-processus" }, { label: "Procédures & documentation", href: "/gestion-organisation/procedures-documentation" }, { label: "Pilotage de la performance", href: "/gestion-organisation/pilotage-performance" }],
    primaryLabel: "Demander un diagnostic organisationnel",
    whatsappMessage: whatsappMessages.organisation,
    seoTitle: "Conseil en organisation d’entreprise au Maroc",
    seoDescription: "Structuration des processus, rôles, procédures, KPI et pilotage pour les entreprises et PME au Maroc.",
  },
  {
    path: "gestion-organisation/organisation-processus",
    eyebrow: "Organisation · Processus",
    title: "Clarifier comment le travail circule et où il se bloque.",
    description: "Une cartographie utile relie les besoins clients, les activités, les acteurs et les résultats attendus pour améliorer le fonctionnement réel.",
    image: "/photos/organisation.jpg",
    imageAlt: "Cartographie et organisation des processus",
    problems: ["Interfaces floues entre services", "Doublons et attentes", "Dépendance à certaines personnes", "Responsabilités contestées"],
    objectives: ["Visualiser les flux", "Réduire les ruptures", "Définir les pilotes", "Prioriser les améliorations"],
    steps: sharedSteps,
    deliverables: ["Cartographie macro", "Fiches processus", "Matrice RACI", "Plan d’optimisation"],
    benefits: ["Flux plus fluides", "Rôles clairs", "Risques identifiés", "Base solide pour digitaliser"],
    audience: ["Directions", "Responsables de service", "Qualité", "PME en croissance"],
    examples: ["Processus commande-livraison", "Traitement des réclamations", "Processus administratif"],
    faq: [{ question: "Une cartographie doit-elle être complexe ?", answer: "Non. Elle doit surtout être comprise par les équipes et permettre des décisions." }, { question: "Qui devient pilote de processus ?", answer: "Le rôle est attribué à la personne capable de coordonner les contributeurs et de suivre le résultat global." }, { question: "Peut-on digitaliser ensuite ?", answer: "Oui. La clarification du processus réduit fortement le risque de digitaliser des étapes inutiles." }],
    related: [{ label: "Digitalisation des processus", href: "/digitalisation/digitalisation-processus" }, { label: "Procédures utiles", href: "/gestion-organisation/procedures-documentation" }],
    primaryLabel: "Cartographier mes processus",
    whatsappMessage: whatsappMessages.organisation,
    seoTitle: "Organisation et cartographie des processus",
    seoDescription: "Cartographie des processus, responsabilités et optimisation des flux pour structurer votre entreprise.",
  },
  {
    path: "gestion-organisation/procedures-documentation",
    eyebrow: "Organisation · Documentation",
    title: "Créer des procédures que les équipes utilisent vraiment.",
    description: "LIDA construit un système documentaire proportionné, facile à maintenir et directement relié aux pratiques de travail.",
    image: "/photos/organisation.jpg",
    imageAlt: "Procédures et documentation d’entreprise",
    problems: ["Savoir détenu oralement", "Documents obsolètes", "Modèles dispersés", "Nouveaux collaborateurs difficiles à intégrer"],
    objectives: ["Préserver le savoir-faire", "Uniformiser les pratiques critiques", "Maîtriser les versions", "Faciliter la formation"],
    steps: [{ title: "Inventorier", text: "Identifier les documents existants et les activités qui nécessitent un repère." }, { title: "Prioriser", text: "Cibler les procédures utiles selon le risque et la fréquence." }, { title: "Rédiger avec le terrain", text: "Formaliser des instructions claires avec les utilisateurs." }, { title: "Maintenir", text: "Définir validation, diffusion, révision et archivage." }],
    deliverables: ["Architecture documentaire", "Procédures et modes opératoires", "Modèles de documents", "Règles de gestion documentaire"],
    benefits: ["Pratiques stabilisées", "Transmission facilitée", "Erreurs réduites", "Audits mieux préparés"],
    audience: ["Administration", "Opérations", "Qualité et QHSE", "Entreprises préparant une certification"],
    examples: ["Procédure achats", "Gestion des documents", "Guide d’intégration"],
    faq: [{ question: "Qui valide les procédures ?", answer: "Le responsable de l’activité valide le contenu, selon un circuit défini avec la direction." }, { question: "Pouvez-vous reprendre nos documents ?", answer: "Oui. LIDA trie, simplifie et harmonise l’existant avant de créer de nouveaux documents." }, { question: "Comment maintenir la documentation ?", answer: "Des propriétaires, dates de revue et règles de version sont définis dès la conception." }],
    related: [{ label: "ISO 9001", href: "/accompagnement-iso/iso-9001" }, { label: "Gestion administrative", href: "/formation/gestion-administrative-comptable" }],
    primaryLabel: "Structurer ma documentation",
    whatsappMessage: whatsappMessages.organisation,
    seoTitle: "Procédures et documentation d’entreprise",
    seoDescription: "Création et simplification de procédures, modes opératoires et systèmes documentaires pour les PME.",
  },
  {
    path: "gestion-organisation/pilotage-performance",
    eyebrow: "Organisation · Pilotage",
    title: "Installer un pilotage qui déclenche des actions.",
    description: "LIDA relie objectifs, KPI, reporting et plans d’action dans un rythme de management adapté à votre activité.",
    image: "/photos/organisation.jpg",
    imageAlt: "Pilotage de la performance et indicateurs KPI",
    problems: ["Réunions sans décisions", "Données arrivant trop tard", "Plans d’action non suivis", "Objectifs non déclinés"],
    objectives: ["Choisir les bons KPI", "Fiabiliser le reporting", "Responsabiliser les pilotes", "Suivre les décisions"],
    steps: sharedSteps,
    deliverables: ["Tableau de bord", "Fiches indicateurs", "Rituels de pilotage", "Registre des décisions et actions"],
    benefits: ["Décisions tracées", "Alertes précoces", "Priorités visibles", "Responsables autonomes"],
    audience: ["Directions", "Managers", "Contrôle de gestion", "Qualité et QHSE"],
    examples: ["Comité mensuel de performance", "Tableau de bord multi-services", "Pilotage d’un plan de progrès"],
    faq: [{ question: "Quelle fréquence de pilotage choisir ?", answer: "Elle dépend du rythme de l’activité : certains indicateurs sont quotidiens, d’autres mensuels ou trimestriels." }, { question: "Comment éviter les réunions trop longues ?", answer: "L’ordre du jour est centré sur les écarts, les décisions et les actions, pas sur la lecture exhaustive des chiffres." }, { question: "Peut-on automatiser le reporting ?", answer: "Oui, après avoir stabilisé les définitions et les sources de données." }],
    related: [{ label: "Tableaux de bord", href: "/digitalisation/tableaux-de-bord" }, { label: "Optimisation de la performance", href: "/conseil-accompagnement/optimisation-performance" }],
    primaryLabel: "Améliorer mon pilotage",
    whatsappMessage: whatsappMessages.organisation,
    seoTitle: "Pilotage de la performance et KPI",
    seoDescription: "KPI, reporting, revues de performance et plans d’action pour piloter votre entreprise avec méthode.",
  },
  {
    path: "accompagnement-iso",
    eyebrow: "Accompagnement ISO",
    title: "Préparer votre certification avec un système utile au terrain.",
    description: "Du diagnostic initial à la préparation de l’audit, LIDA accompagne vos équipes pour construire un système de management compris, appliqué et durable.",
    image: "/photos/iso.jpg",
    imageAlt: "Accompagnement à la certification ISO",
    problems: ["Exigences normatives difficiles à traduire", "Documentation déconnectée du terrain", "Échéance de certification à sécuriser", "Équipes peu sensibilisées"],
    objectives: ["Évaluer les écarts", "Déployer un système proportionné", "Former les acteurs", "Préparer sereinement l’audit de certification"],
    steps: [{ title: "Diagnostic initial", text: "Analyse des pratiques et des écarts par rapport au référentiel choisi." }, { title: "Plan d’action", text: "Priorisation des exigences, responsables, ressources et échéances." }, { title: "Mise en œuvre", text: "Documentation, formation, déploiement et collecte des preuves de fonctionnement." }, { title: "Préparation à l’audit", text: "Audit interne, traitement des écarts et audit blanc avant certification." }],
    deliverables: ["Rapport d’écarts", "Plan d’action ISO", "Système documentaire", "Audit interne et audit blanc"],
    benefits: ["Projet maîtrisé", "Équipes impliquées", "Documents utiles", "Certification mieux préparée"],
    audience: ["PME", "Industries", "Services", "Organisations souhaitant structurer ou faire évoluer leur système de management"],
    examples: ["Préparation ISO 9001", "Système environnemental ISO 14001", "Management SST ISO 45001"],
    faq: [{ question: "LIDA délivre-t-elle la certification ?", answer: "Non. LIDA accompagne et prépare l’entreprise. La certification est délivrée par un organisme certificateur indépendant." }, { question: "Combien de temps faut-il ?", answer: "La durée dépend de la taille, du périmètre et de la maturité de l’organisation. Le diagnostic initial permet d’établir un calendrier réaliste." }, { question: "Réalisez-vous les audits internes ?", answer: "Oui, dans le respect de l’indépendance nécessaire par rapport aux activités auditées." }],
    related: [{ label: "Organisation & processus", href: "/gestion-organisation" }, { label: "Formation QHSE", href: "/formation/qhse" }],
    children: [{ label: "ISO 9001 · Qualité", href: "/accompagnement-iso/iso-9001" }, { label: "ISO 14001 · Environnement", href: "/accompagnement-iso/iso-14001" }, { label: "ISO 45001 · Santé et sécurité", href: "/accompagnement-iso/iso-45001" }],
    primaryLabel: "Demander un diagnostic ISO",
    whatsappMessage: whatsappMessages.iso,
    seoTitle: "Accompagnement ISO au Maroc",
    seoDescription: "Accompagnement ISO 9001, ISO 14001 et ISO 45001 au Maroc : diagnostic, documentation, formation, audit interne et préparation certification.",
  },
  ...([ 
    {
      code: "9001", name: "Qualité", purpose: "structurer la qualité autour des besoins clients et de l’amélioration continue", imageAlt: "Accompagnement à la certification ISO 9001",
      advantages: ["Satisfaction client mieux pilotée", "Processus maîtrisés", "Non-conformités traitées", "Amélioration continue structurée"],
      audience: ["PME de services ou industrielles", "Entreprises répondant à des appels d’offres", "Organisations souhaitant fiabiliser leurs processus"],
      examples: ["Cartographie des processus qualité", "Traitement des réclamations", "Préparation de la revue de direction"],
      faq: [{ question: "Une PME peut-elle être certifiée ISO 9001 ?", answer: "Oui. Les exigences s’appliquent de manière proportionnée à la taille, aux activités et aux risques de l’organisation." }, { question: "Quelle différence entre accompagnement et certification ?", answer: "L’accompagnement prépare le système et les équipes. L’audit de certification est conduit par un organisme indépendant." }, { question: "Comment démarrer un projet ISO 9001 ?", answer: "Un diagnostic initial permet de connaître les écarts, puis de construire un plan d’action réaliste." }],
      related: [{ label: "Organisation des processus", href: "/gestion-organisation/organisation-processus" }, { label: "Formation ISO 9001", href: "/formation/iso-9001" }],
    },
    {
      code: "14001", name: "Environnement", purpose: "identifier, maîtriser et améliorer les impacts environnementaux de l’activité", imageAlt: "Accompagnement à la certification ISO 14001",
      advantages: ["Aspects environnementaux priorisés", "Obligations mieux suivies", "Risques et consommations maîtrisés", "Performance environnementale mesurée"],
      audience: ["Industries", "BTP", "Logistique", "Services souhaitant structurer leurs engagements environnementaux"],
      examples: ["Analyse des aspects environnementaux", "Suivi des déchets et consommations", "Préparation aux situations d’urgence"],
      faq: [{ question: "ISO 14001 impose-t-elle des objectifs précis ?", answer: "L’organisation fixe ses objectifs selon ses aspects significatifs, ses obligations et son contexte, puis démontre ses progrès." }, { question: "Faut-il déjà être conforme à toute la réglementation ?", answer: "La conformité réglementaire est une exigence centrale. Le diagnostic identifie les écarts et organise leur traitement." }, { question: "Peut-on intégrer ISO 14001 à ISO 9001 ?", answer: "Oui. Les deux normes partagent une structure compatible permettant un système de management intégré." }],
      related: [{ label: "Formation ISO 14001", href: "/formation/iso-14001" }, { label: "Gestion documentaire", href: "/gestion-organisation/procedures-documentation" }],
    },
    {
      code: "45001", name: "Santé et sécurité", purpose: "prévenir les accidents, les maladies professionnelles et améliorer les conditions de travail", imageAlt: "Accompagnement à la certification ISO 45001",
      advantages: ["Dangers et risques mieux évalués", "Participation des travailleurs", "Plans de prévention suivis", "Culture sécurité renforcée"],
      audience: ["Industrie", "BTP", "Transport", "Services exposés à des risques professionnels"],
      examples: ["Évaluation des risques SST", "Gestion des incidents", "Préparation et réponse aux urgences"],
      faq: [{ question: "ISO 45001 concerne-t-elle uniquement l’industrie ?", answer: "Non. Toute organisation employant des personnes peut structurer la prévention selon ses propres risques." }, { question: "Quel est le rôle des travailleurs ?", answer: "La consultation et la participation des travailleurs sont essentielles pour identifier les risques et construire des mesures applicables." }, { question: "LIDA réalise-t-elle un audit blanc ?", answer: "Oui. L’audit blanc vérifie la préparation du système et aide à traiter les écarts avant la certification." }],
      related: [{ label: "Formation ISO 45001", href: "/formation/iso-45001" }, { label: "Formation QHSE", href: "/formation/qhse" }],
    },
  ] as const).map((standard): ServicePageData => ({
    path: `accompagnement-iso/iso-${standard.code}`,
    eyebrow: `Accompagnement ISO ${standard.code}`,
    title: `Faire de l’ISO ${standard.code} un système de management vivant.`,
    description: `LIDA accompagne votre entreprise pour ${standard.purpose}, depuis l’analyse initiale jusqu’à la préparation de l’audit de certification.`,
    image: "/photos/iso.jpg",
    imageAlt: standard.imageAlt,
    problems: ["Exigences difficiles à interpréter", "Pratiques non formalisées", "Preuves de fonctionnement dispersées", "Audit de certification à préparer"],
    objectives: [`Comprendre les exigences ISO ${standard.code}`, "Analyser les écarts", "Mettre en conformité les pratiques", "Accompagner jusqu’à la certification"],
    steps: [{ title: "Diagnostic initial", text: `Évaluation du système existant face aux exigences ISO ${standard.code}.` }, { title: "Plan d’action", text: "Priorisation des écarts, responsables, ressources et échéances." }, { title: "Déploiement", text: "Documentation, procédures, formation, sensibilisation et mise en pratique." }, { title: "Audits", text: "Audit interne, traitement des écarts et préparation de l’audit de certification." }],
    deliverables: ["Diagnostic et analyse des écarts", "Plan d’action", "Documentation et procédures", "Formation, audit interne et audit blanc"],
    benefits: [...standard.advantages],
    audience: [...standard.audience],
    examples: [...standard.examples],
    faq: [...standard.faq],
    related: [...standard.related],
    primaryLabel: `Demander un diagnostic ISO ${standard.code}`,
    whatsappMessage: `Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre accompagnement ISO ${standard.code}.`,
    seoTitle: `Accompagnement ISO ${standard.code} au Maroc`,
    seoDescription: `Accompagnement à la certification ISO ${standard.code} au Maroc : diagnostic, plan d’action, documentation, formation, audit interne et audit blanc.`,
  })),
];

export const servicePages = Object.fromEntries(pages.map((page) => [page.path, page]));
export const servicePaths = pages.map((page) => page.path);
