import type { FaqItem, LinkItem } from "@/app/_data/services";

export type TrainingData = {
  slug: string;
  title: string;
  shortTitle: string;
  category: "Gestion" | "Comptabilité" | "Fiscalité" | "Intelligence Artificielle" | "Excel" | "VBA" | "Management" | "QHSE" | "ISO";
  level: string;
  duration: string;
  description: string;
  promise: string;
  image: string;
  imageAlt?: string;
  why: string[];
  objectives: string[];
  program: { title: string; items: string[] }[];
  skills: string[];
  audience: string[];
  prerequisites: string;
  format: string;
  whatsappMessage: string;
  related: LinkItem[];
  faq: FaqItem[];
  seoTitle: string;
  seoDescription: string;
};

const practicalFaq: FaqItem[] = [
  { question: "La formation peut-elle être organisée en entreprise ?", answer: "Oui. Le format intra-entreprise permet d’adapter les cas pratiques, le rythme et les objectifs à votre équipe." },
  { question: "Peut-on suivre la formation à distance ?", answer: "Selon le programme, la formation peut être organisée en présentiel, à distance ou dans un format hybride." },
  { question: "Une attestation est-elle délivrée ?", answer: "Les modalités administratives et l’attestation prévue sont précisées dans la proposition de formation." },
  { question: "Peut-on adapter le programme ?", answer: "Oui. Un échange de cadrage et, si nécessaire, un positionnement permettent de cibler les modules utiles." },
];

export const trainings: TrainingData[] = [
  {
    slug: "gestion-administrative-comptable",
    title: "Gestion administrative et comptable des sociétés",
    shortTitle: "Gestion administrative & comptable",
    category: "Comptabilité",
    level: "Fondamentaux à opérationnel",
    duration: "À définir après positionnement",
    description: "Structurer les documents, les échéances, la facturation, la trésorerie et la relation avec le cabinet comptable.",
    promise: "Mettre en place une gestion administrative fiable, organisée et facile à suivre.",
    image: "/photos/formation.jpg",
    why: ["Réduire les oublis d’échéances", "Fiabiliser les pièces transmises au comptable", "Mieux suivre clients, fournisseurs et trésorerie", "Créer des tableaux de gestion simples"],
    objectives: ["Organiser le classement et l’archivage", "Maîtriser le cycle de facturation", "Suivre règlements et trésorerie", "Préparer correctement les pièces comptables"],
    program: [{ title: "Organisation administrative", items: ["Documents de l’entreprise", "Classement et archivage", "Échéancier administratif", "Gestion documentaire"] }, { title: "Flux clients et fournisseurs", items: ["Devis et factures", "Suivi des règlements", "Relances", "Dossiers fournisseurs"] }, { title: "Bases comptables", items: ["Notions essentielles", "Pièces justificatives", "Préparation des dossiers", "Relation avec le cabinet comptable"] }, { title: "Pilotage", items: ["Suivi de trésorerie", "Tableaux clients/fournisseurs", "Indicateurs administratifs", "Bonnes pratiques de contrôle"] }],
    skills: ["Tenir un dossier administratif structuré", "Suivre les échéances", "Préparer les pièces comptables", "Construire des tableaux de suivi"],
    audience: ["Dirigeants", "Entrepreneurs", "Responsables et assistants administratifs", "Responsables financiers", "Créateurs d’entreprise"],
    prerequisites: "Aucun prérequis comptable avancé. Les participants peuvent apporter leurs modèles de documents pour les ateliers.",
    format: "Présentiel, à distance ou intra-entreprise avec cas adaptés à l’organisation.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Gestion administrative et comptable des sociétés.",
    related: [{ label: "Optimisation fiscale", href: "/formation/optimisation-fiscale" }, { label: "Excel professionnel", href: "/formation/excel" }],
    faq: practicalFaq,
    seoTitle: "Formation gestion administrative et comptable au Maroc",
    seoDescription: "Formation professionnelle en gestion administrative, facturation, trésorerie et préparation comptable pour dirigeants et équipes au Maroc.",
  },
  {
    slug: "optimisation-fiscale",
    title: "Optimisation fiscale dans un cadre légal et conforme",
    shortTitle: "Optimisation fiscale",
    category: "Fiscalité",
    level: "Fondamentaux",
    duration: "Programme adaptable",
    description: "Comprendre, anticiper et organiser la fiscalité de l’entreprise sans jamais confondre optimisation légale et évitement illicite de l’impôt.",
    promise: "Prendre de meilleures décisions fiscales dans un cadre documenté, prudent et conforme.",
    image: "/photos/formation.jpg",
    why: ["Anticiper les échéances", "Améliorer la qualité des justificatifs", "Limiter les risques de non-conformité", "Mieux coordonner direction, comptabilité et fiscalité"],
    objectives: ["Comprendre les principaux mécanismes fiscaux", "Organiser le calendrier fiscal", "Identifier les options légales pertinentes", "Préparer les éléments en cas de contrôle"],
    program: [{ title: "Cadre fiscal de l’entreprise", items: ["Principaux impôts et obligations", "Responsabilités", "Calendrier fiscal", "Veille et coordination"] }, { title: "Organisation et justificatifs", items: ["Pièces probantes", "Traçabilité", "Archivage", "Rapprochements"] }, { title: "Optimisation conforme", items: ["Arbitrages documentés", "Anticipation", "Choix légalement permis", "Validation avec les professionnels compétents"] }, { title: "Gestion des risques", items: ["Signaux d’alerte", "Préparation au contrôle", "Dossier permanent", "Plan d’amélioration"] }],
    skills: ["Lire un calendrier fiscal", "Structurer les justificatifs", "Évaluer un risque", "Dialoguer efficacement avec le conseil fiscal et le comptable"],
    audience: ["Dirigeants", "Responsables administratifs et financiers", "Comptables d’entreprise", "Entrepreneurs"],
    prerequisites: "Connaître le fonctionnement général de son entreprise. La formation ne remplace pas une consultation fiscale individualisée.",
    format: "Formation en présentiel, à distance ou en intra-entreprise, avec exercices de conformité et d’organisation.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Optimisation fiscale.",
    related: [{ label: "Gestion administrative & comptable", href: "/formation/gestion-administrative-comptable" }, { label: "Organisation documentaire", href: "/gestion-organisation/documentation-conformite" }],
    faq: [{ question: "La formation explique-t-elle comment éviter l’impôt ?", answer: "Non. Elle traite uniquement d’organisation, d’anticipation et d’options légales conformes aux règles applicables." }, { question: "Remplace-t-elle le conseil d’un fiscaliste ?", answer: "Non. Elle donne des repères de gestion et aide à préparer les échanges avec les professionnels compétents." }, ...practicalFaq.slice(0, 2)],
    seoTitle: "Formation optimisation fiscale au Maroc",
    seoDescription: "Formation à l’optimisation fiscale légale : organisation, échéances, justificatifs, risques et préparation aux contrôles.",
  },
  {
    slug: "gestion-intelligence-artificielle",
    title: "Optimisation de la gestion par Intelligence Artificielle",
    shortTitle: "IA pour la gestion",
    category: "Intelligence Artificielle",
    level: "Pratique · Tous niveaux",
    duration: "Programme modulable",
    description: "Utiliser l’IA de façon concrète et responsable pour gagner du temps sur les tâches administratives, l’analyse, le reporting et la préparation des décisions.",
    promise: "Passer de la curiosité à des usages IA utiles, sécurisés et reproductibles.",
    image: "/photos/digitalisation.jpg",
    why: ["Automatiser des tâches à faible valeur", "Améliorer la qualité des documents", "Accélérer l’analyse et le reporting", "Encadrer confidentialité et vérification"],
    objectives: ["Identifier les cas d’usage rentables", "Rédiger des instructions efficaces", "Vérifier les résultats produits", "Définir des règles d’utilisation professionnelle"],
    program: [{ title: "Fondamentaux et cadre d’usage", items: ["Fonctionnement général", "Limites et erreurs", "Confidentialité des données", "Charte de bonnes pratiques"] }, { title: "Productivité administrative", items: ["Emails", "Comptes rendus", "Procédures", "Analyse documentaire", "Préparation de réunions"] }, { title: "Données et reporting", items: ["Analyse de tableaux", "Rapports", "Aide aux dashboards", "Modèles Excel", "Support à la décision"] }, { title: "Mise en pratique", items: ["Cas métiers", "Bibliothèque de prompts", "Workflow humain + IA", "Plan d’adoption"] }],
    skills: ["Utiliser professionnellement ChatGPT et des outils IA", "Créer des prompts réutilisables", "Analyser et contrôler un résultat", "Protéger les données sensibles"],
    audience: ["Dirigeants", "Managers", "Administratifs", "RH", "Finance", "Qualité et QHSE"],
    prerequisites: "Aucun niveau technique requis. Une connaissance de ses tâches quotidiennes suffit pour travailler sur des cas concrets.",
    format: "Ateliers guidés en présentiel, à distance ou dans votre entreprise, avec cas d’usage adaptés aux métiers.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Optimisation de la gestion par Intelligence Artificielle.",
    related: [{ label: "Automatisation & ERP", href: "/digitalisation/automatisation-integration-erp" }, { label: "Excel professionnel", href: "/formation/excel" }],
    faq: [{ question: "Faut-il savoir programmer ?", answer: "Non. La formation se concentre sur les usages de gestion et les méthodes de travail, sans prérequis de développement." }, { question: "Peut-on utiliser des documents de l’entreprise ?", answer: "Oui uniquement si les règles de confidentialité sont respectées. Des cas anonymisés peuvent être utilisés." }, ...practicalFaq.slice(0, 2)],
    seoTitle: "Formation Intelligence Artificielle entreprise au Maroc",
    seoDescription: "Formation pratique à l’IA pour les entreprises : ChatGPT, automatisation administrative, analyse, reporting et confidentialité.",
  },
  {
    slug: "excel",
    title: "Excel professionnel — débutant, intermédiaire et avancé",
    shortTitle: "Excel professionnel",
    category: "Excel",
    level: "Débutant à avancé",
    duration: "Selon le niveau choisi",
    description: "Maîtriser les fonctions, les données, les tableaux croisés dynamiques, les graphiques et le reporting à travers des exercices professionnels.",
    promise: "Transformer des données dispersées en analyses fiables et directement exploitables.",
    image: "/photos/formation.jpg",
    why: ["Gagner du temps dans les calculs", "Fiabiliser les fichiers", "Analyser de grands tableaux", "Présenter des indicateurs lisibles"],
    objectives: ["Choisir les bonnes formules", "Structurer et nettoyer les données", "Créer des analyses dynamiques", "Construire des tableaux de bord"],
    program: [{ title: "Niveau débutant", items: ["Interface et bonnes pratiques", "Formules de base", "Mise en forme", "Tri, filtre et impression"] }, { title: "Niveau intermédiaire", items: ["Fonctions conditionnelles", "Recherche de données", "Validation", "Tableaux structurés", "Graphiques"] }, { title: "Niveau avancé", items: ["Fonctions avancées", "Nettoyage de données", "Tableaux croisés dynamiques", "Modèles de reporting"] }, { title: "Projet pratique", items: ["Base de données", "KPI", "Dashboard", "Contrôles de fiabilité"] }],
    skills: ["Construire des formules robustes", "Nettoyer une base", "Créer un tableau croisé dynamique", "Produire un reporting professionnel"],
    audience: ["Administratifs", "Commerciaux", "Finance", "RH", "Managers", "Qualité et QHSE"],
    prerequisites: "Un test de positionnement permet d’orienter le participant vers le niveau débutant, intermédiaire ou avancé.",
    format: "Présentiel, distanciel ou intra-entreprise, avec fichiers d’exercices et cas métiers.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Excel.",
    related: [{ label: "Aller plus loin avec Excel VBA", href: "/formation/excel-vba" }, { label: "Tableaux de bord", href: "/digitalisation/tableaux-de-bord-automatises" }],
    faq: [{ question: "Comment choisir mon niveau ?", answer: "Un positionnement rapide évalue les acquis et les tâches à maîtriser afin de recommander le bon parcours." }, { question: "Les exercices peuvent-ils utiliser nos modèles ?", answer: "Oui, en intra-entreprise, à condition de transmettre des fichiers anonymisés et exploitables." }, ...practicalFaq.slice(0, 2)],
    seoTitle: "Formation Excel au Maroc — tous niveaux",
    seoDescription: "Formation Excel professionnelle au Maroc : formules, données, tableaux croisés dynamiques, graphiques, tableaux de bord et reporting.",
  },
  {
    slug: "excel-vba",
    title: "Excel VBA — automatiser les tâches et les outils de gestion",
    shortTitle: "Excel VBA",
    category: "VBA",
    level: "Intermédiaire à avancé",
    duration: "Selon le projet et le niveau",
    description: "Apprendre à créer des macros, automatiser des rapports et construire des outils de gestion adaptés aux besoins de l’entreprise.",
    promise: "Transformer Excel en véritable outil de gestion automatisé.",
    image: "/photos/digitalisation.jpg",
    why: ["Éliminer les manipulations répétitives", "Réduire les risques d’erreur", "Générer automatiquement rapports et documents", "Créer des interfaces simples"],
    objectives: ["Comprendre la logique VBA", "Manipuler feuilles, fichiers et données", "Automatiser un processus", "Créer un outil maintenable"],
    program: [{ title: "Premières macros", items: ["Enregistreur", "Éditeur VBA", "Objets Excel", "Bonnes pratiques"] }, { title: "Logique de programmation", items: ["Variables", "Conditions", "Boucles", "Procédures et fonctions"] }, { title: "Automatisation", items: ["Feuilles et classeurs", "Fichiers", "Import/export", "Génération de rapports"] }, { title: "Outils de gestion", items: ["Formulaires VBA", "Contrôles", "Gestion des erreurs", "Projet métier"] }],
    skills: ["Écrire et corriger une macro", "Automatiser un reporting", "Créer un formulaire", "Structurer un mini-outil de gestion"],
    audience: ["Utilisateurs Excel réguliers", "Contrôleurs de gestion", "Finance", "Administratifs", "Analystes et responsables reporting"],
    prerequisites: "Maîtriser les bases d’Excel, les formules courantes et la manipulation de tableaux de données.",
    format: "Ateliers pratiques en présentiel, à distance ou en intra-entreprise autour d’un cas d’automatisation.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Excel VBA.",
    related: [{ label: "Préparer les bases avec Excel", href: "/formation/excel" }, { label: "Outils de gestion", href: "/digitalisation/outils-gestion-management" }],
    faq: [{ question: "VBA est-il adapté à tous les projets ?", answer: "Non. La formation aide aussi à reconnaître les situations où une autre solution serait plus robuste." }, { question: "Peut-on travailler sur une automatisation réelle ?", answer: "Oui en intra-entreprise, après cadrage du besoin, des fichiers disponibles et des règles de confidentialité." }, ...practicalFaq.slice(0, 2)],
    seoTitle: "Formation Excel VBA au Maroc",
    seoDescription: "Formation Excel VBA : macros, boucles, formulaires, automatisation des rapports et création d’outils de gestion.",
  },
  {
    slug: "management",
    title: "Management opérationnel",
    shortTitle: "Management",
    category: "Management",
    level: "Managers et futurs managers",
    duration: "Parcours adaptable",
    description: "Développer des pratiques concrètes pour fixer les priorités, déléguer, animer les équipes et suivre les engagements.",
    promise: "Manager avec des repères clairs, une communication directe et des routines utiles.",
    image: "/photos/conseil.jpg",
    why: ["Clarifier les attentes", "Mieux déléguer", "Gérer les situations difficiles", "Faire progresser l’équipe"],
    objectives: ["Adapter son management", "Conduire un entretien", "Animer une réunion", "Piloter un plan d’action"],
    program: [{ title: "Rôle du manager", items: ["Positionnement", "Objectifs", "Responsabilités", "Styles de management"] }, { title: "Communication", items: ["Écoute", "Feedback", "Recadrage", "Entretiens"] }, { title: "Pilotage", items: ["Délégation", "Rituels", "Indicateurs", "Suivi des actions"] }, { title: "Situations réelles", items: ["Mises en situation", "Études de cas", "Plan de progrès", "Retours d’expérience"] }],
    skills: ["Déléguer avec un cadre", "Donner du feedback", "Animer une réunion", "Suivre les priorités"],
    audience: ["Managers de proximité", "Responsables de service", "Chefs de projet", "Futurs managers"],
    prerequisites: "Aucun prérequis formel. Les participants viennent avec des situations managériales à travailler.",
    format: "Ateliers participatifs, mises en situation et accompagnement intra-entreprise.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Management.",
    related: [{ label: "Processus & responsabilités", href: "/gestion-organisation/processus-responsabilites" }],
    faq: practicalFaq,
    seoTitle: "Formation management au Maroc",
    seoDescription: "Formation en management opérationnel : délégation, communication, réunions, feedback et pilotage des équipes.",
  },
  {
    slug: "qhse",
    title: "Fondamentaux QHSE",
    shortTitle: "QHSE",
    category: "QHSE",
    level: "Fondamentaux à perfectionnement",
    duration: "Selon les modules retenus",
    description: "Comprendre et coordonner les enjeux qualité, hygiène, sécurité et environnement dans une approche pratique.",
    promise: "Donner aux acteurs QHSE les méthodes pour prévenir, mesurer et améliorer.",
    image: "/photos/iso.jpg",
    why: ["Structurer la prévention", "Comprendre les obligations", "Analyser les incidents", "Déployer des actions QHSE"],
    objectives: ["Identifier les risques", "Construire un plan QHSE", "Suivre des indicateurs", "Animer la sensibilisation"],
    program: [{ title: "Système QHSE", items: ["Principes", "Rôles", "Risques et opportunités", "Planification"] }, { title: "Prévention", items: ["Identification des dangers", "Évaluation", "Mesures de maîtrise", "Urgences"] }, { title: "Pilotage", items: ["Indicateurs", "Incidents", "Actions correctives", "Audits"] }, { title: "Animation", items: ["Sensibilisation", "Communication", "Causeries", "Amélioration continue"] }],
    skills: ["Évaluer un risque", "Suivre un plan d’action", "Analyser un incident", "Préparer une sensibilisation"],
    audience: ["Responsables QHSE", "Managers", "Préventeurs", "Membres de comités sécurité"],
    prerequisites: "Aucun pour le tronc commun. Certains modules avancés nécessitent une première expérience QHSE.",
    format: "Modules en présentiel, à distance ou sur site, avec exercices liés aux risques de l’activité.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation QHSE.",
    related: [{ label: "Accompagnement ISO", href: "/accompagnement-iso" }, { label: "ISO 45001", href: "/formation/iso-45001" }],
    faq: practicalFaq,
    seoTitle: "Formation QHSE au Maroc",
    seoDescription: "Formation QHSE au Maroc : risques, prévention, indicateurs, incidents, audits et amélioration continue.",
  },
  ...(["9001", "14001", "45001"] as const).map((code): TrainingData => {
    const labels = { "9001": "management de la qualité", "14001": "management environnemental", "45001": "management de la santé et sécurité au travail" };
    const topics = {
      "9001": ["Contexte et parties intéressées", "Approche processus", "Satisfaction client", "Non-conformités et amélioration"],
      "14001": ["Aspects environnementaux", "Obligations de conformité", "Perspective cycle de vie", "Urgences environnementales"],
      "45001": ["Dangers et risques SST", "Consultation des travailleurs", "Maîtrise opérationnelle", "Incidents et urgences"],
    };
    return {
      slug: `iso-${code}`,
      title: `Comprendre et appliquer l’ISO ${code}`,
      shortTitle: `ISO ${code}`,
      category: "ISO",
      level: "Initiation à mise en œuvre",
      duration: "Selon le niveau visé",
      description: `Maîtriser les principes et les exigences de l’ISO ${code} pour contribuer efficacement à un système de ${labels[code]}.`,
      promise: `Traduire les exigences ISO ${code} en pratiques concrètes dans votre organisation.`,
      image: code === "9001" ? "/photos/conseil.jpg" : "/photos/iso.jpg",
      imageAlt: code === "9001"
        ? "Équipe analysant des indicateurs pour une formation au management de la qualité ISO 9001"
        : code === "45001"
          ? "Professionnel portant un casque et un gilet haute visibilité pour une formation ISO 45001 en sécurité au travail"
          : undefined,
      why: ["Comprendre le référentiel", "Participer au projet de certification", "Préparer les preuves", "Contribuer aux audits et améliorations"],
      objectives: ["Lire la structure de la norme", "Interpréter les exigences", "Identifier les preuves attendues", "Construire un plan d’application"],
      program: [{ title: "Fondamentaux", items: ["Principes de management", "Structure de la norme", "Vocabulaire", "Rôles"] }, { title: `Exigences ISO ${code}`, items: topics[code] }, { title: "Mise en œuvre", items: ["Diagnostic", "Documentation utile", "Indicateurs", "Plan d’action"] }, { title: "Évaluation", items: ["Audit interne", "Écarts", "Actions correctives", "Revue de direction"] }],
      skills: [`Interpréter l’ISO ${code}`, "Relier exigence et pratique", "Préparer une preuve", "Contribuer à un audit"],
      audience: ["Responsables et animateurs QHSE", "Pilotes de processus", "Managers", "Auditeurs internes débutants"],
      prerequisites: "Aucun pour l’initiation. Une connaissance de l’organisation est utile pour les ateliers d’application.",
      format: "Présentiel, distanciel ou intra-entreprise avec exercices sur votre système de management.",
      whatsappMessage: `Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation ISO ${code}.`,
      related: [{ label: `Accompagnement ISO ${code}`, href: `/accompagnement-iso/iso-${code}` }, { label: "Formation QHSE", href: "/formation/qhse" }],
      faq: practicalFaq,
      seoTitle: `Formation ISO ${code} au Maroc`,
      seoDescription: `Formation ISO ${code} au Maroc : comprendre les exigences, préparer la mise en œuvre et contribuer aux audits internes.`,
    };
  }),
  {
    slug: "organisation",
    title: "Organisation et processus",
    shortTitle: "Organisation",
    category: "Gestion",
    level: "Tous niveaux",
    duration: "Programme adaptable",
    description: "Cartographier les processus, clarifier les rôles et structurer les pratiques sans alourdir le fonctionnement.",
    promise: "Construire une organisation comprise et applicable par les équipes.",
    image: "/photos/organisation.jpg",
    why: ["Réduire les zones grises", "Fluidifier les interfaces", "Transmettre le savoir-faire", "Préparer la digitalisation"],
    objectives: ["Cartographier un processus", "Définir les responsabilités", "Rédiger une procédure utile", "Identifier les améliorations"],
    program: [{ title: "Lecture de l’organisation", items: ["Activités", "Processus", "Interfaces", "Parties prenantes"] }, { title: "Rôles", items: ["Organigramme", "Responsabilités", "RACI", "Délégation"] }, { title: "Formalisation", items: ["Fiche processus", "Procédures", "Documents", "Gestion des versions"] }, { title: "Amélioration", items: ["Irritants", "Risques", "KPI", "Plan d’action"] }],
    skills: ["Représenter un processus", "Construire une matrice RACI", "Rédiger une procédure", "Animer une amélioration"],
    audience: ["Managers", "Responsables qualité", "Administratifs", "Pilotes de processus"],
    prerequisites: "Aucun. Les participants peuvent apporter un processus réel à cartographier.",
    format: "Atelier pratique, présentiel ou à distance, particulièrement adapté à l’intra-entreprise.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Organisation.",
    related: [{ label: "Conseil en organisation", href: "/gestion-organisation" }],
    faq: practicalFaq,
    seoTitle: "Formation organisation et processus au Maroc",
    seoDescription: "Formation organisation d’entreprise : processus, rôles, RACI, procédures et amélioration des flux.",
  },
  {
    slug: "gestion",
    title: "Fondamentaux de la gestion d’entreprise",
    shortTitle: "Gestion",
    category: "Gestion",
    level: "Fondamentaux",
    duration: "Parcours modulable",
    description: "Comprendre les mécanismes essentiels de gestion pour suivre l’activité, les ressources, les coûts et les priorités.",
    promise: "Piloter l’entreprise avec des repères simples et des décisions mieux préparées.",
    image: "/photos/organisation.jpg",
    why: ["Lire les principaux chiffres", "Organiser les ressources", "Préparer les décisions", "Suivre un plan d’action"],
    objectives: ["Comprendre les flux de gestion", "Construire un budget simple", "Suivre des indicateurs", "Identifier les écarts"],
    program: [{ title: "Repères de gestion", items: ["Cycle d’activité", "Charges et produits", "Marge", "Trésorerie"] }, { title: "Prévision", items: ["Objectifs", "Budget", "Hypothèses", "Scénarios"] }, { title: "Suivi", items: ["KPI", "Tableau de bord", "Écarts", "Actions"] }, { title: "Décision", items: ["Priorités", "Risques", "Ressources", "Revue de gestion"] }],
    skills: ["Lire un tableau de gestion", "Construire une prévision", "Analyser un écart", "Préparer une revue"],
    audience: ["Entrepreneurs", "Managers", "Responsables administratifs", "Créateurs d’entreprise"],
    prerequisites: "Aucun prérequis financier avancé.",
    format: "Présentiel, distance ou intra-entreprise avec cas chiffrés simplifiés.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Gestion.",
    related: [{ label: "Gestion administrative & comptable", href: "/formation/gestion-administrative-comptable" }, { label: "Excel", href: "/formation/excel" }],
    faq: practicalFaq,
    seoTitle: "Formation gestion d’entreprise au Maroc",
    seoDescription: "Formation aux fondamentaux de la gestion : budget, trésorerie, indicateurs, écarts et pilotage de l’activité.",
  },
  {
    slug: "amelioration-continue",
    title: "Amélioration continue et résolution de problèmes",
    shortTitle: "Amélioration continue",
    category: "QHSE",
    level: "Opérationnel",
    duration: "Programme adaptable",
    description: "Analyser les causes, choisir des actions efficaces et installer un suivi qui empêche les problèmes de revenir.",
    promise: "Passer de la réaction aux problèmes à une amélioration structurée et mesurable.",
    image: "/photos/iso.jpg",
    why: ["Traiter les causes plutôt que les symptômes", "Impliquer les équipes", "Mesurer l’efficacité", "Capitaliser sur les solutions"],
    objectives: ["Décrire un problème factuellement", "Analyser les causes", "Construire un plan d’action", "Vérifier l’efficacité"],
    program: [{ title: "Cadrer", items: ["Faits", "Impact", "Périmètre", "Objectif"] }, { title: "Analyser", items: ["5 pourquoi", "Ishikawa", "Données", "Causes racines"] }, { title: "Agir", items: ["Solutions", "Priorisation", "Plan d’action", "Responsabilités"] }, { title: "Pérenniser", items: ["Mesure d’efficacité", "Standardisation", "Retour d’expérience", "Capitalisation"] }],
    skills: ["Cadrer un problème", "Animer une analyse de causes", "Prioriser des actions", "Mesurer leur efficacité"],
    audience: ["Managers", "Qualité et QHSE", "Production", "Équipes support"],
    prerequisites: "Aucun. Les participants peuvent travailler sur un problème réel anonymisé.",
    format: "Ateliers pratiques en présentiel, à distance ou directement avec une équipe.",
    whatsappMessage: "Bonjour LIDA Solutions & Consulting,\n\nJe souhaite avoir des informations concernant votre formation Amélioration continue.",
    related: [{ label: "Tableaux de bord & KPI", href: "/gestion-organisation/tableaux-de-bord-kpi" }, { label: "ISO 9001", href: "/formation/iso-9001" }],
    faq: practicalFaq,
    seoTitle: "Formation amélioration continue au Maroc",
    seoDescription: "Formation amélioration continue : résolution de problèmes, analyse des causes, plans d’action et mesure d’efficacité.",
  },
];

export const trainingBySlug = Object.fromEntries(trainings.map((training) => [training.slug, training]));
export const trainingCategories = ["Toutes", ...Array.from(new Set(trainings.map((training) => training.category)))] as const;
