import type { Metadata } from "next";
import { LockKeyhole } from "lucide-react";
import { PageHero } from "@/app/_components/PageHero";
import { CTASection } from "@/app/_components/CTASection";
import { whatsappMessages } from "@/app/_lib/site";

export const metadata: Metadata = { title: "Réalisations et cas clients", description: "Architecture des études de cas LIDA : contexte, intervention, solution, résultats et services associés.", alternates: { canonical: "/realisations" }, openGraph: { title: "Réalisations LIDA", description: "Des études de cas publiées uniquement après validation des faits et résultats.", url: "/realisations", images: [{ url: "/photos/pages/realisations.webp", alt: "Réalisations LIDA" }] } };

export default function CaseStudiesPage() {
  return <main><PageHero eyebrow="Réalisations" title="Des missions racontées avec des faits, pas des promesses." description="Cette rubrique accueillera les études de cas validées par les clients : contexte, intervention, résultats observables et enseignements." image="/photos/pages/realisations.webp" imageAlt="Équipe préparant une étude de cas et ses livrables" breadcrumbs={[{ label: "Réalisations", href: "/realisations" }]} primaryLabel="Parler de votre projet" primaryHref="/contact" whatsappMessage={whatsappMessages.general} />
    <section className="section"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow eyebrow-dark"><span /> Cas clients</p><h2>Une structure prête pour des références validées.</h2></div><p>Aucun client, témoignage, résultat ou indicateur n’est inventé. Les cas seront publiés uniquement après validation des informations et du niveau de confidentialité.</p></div><div className="placeholder-grid">{["Conseil & organisation", "Digitalisation & pilotage", "ISO & QHSE"].map((title) => <article key={title}><LockKeyhole aria-hidden="true" /><small>Emplacement réservé</small><h2>{title}</h2><p>Cas client à documenter et valider : contexte, problématique, intervention, solution, résultats et services associés.</p></article>)}</div></div></section>
    <section className="section light-section"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow-dark"><span /> Structure d’une étude de cas</p><h2>Un format clair pour démontrer la valeur.</h2></div><ol className="process-grid process-light"><li><span>01</span><h3>Contexte</h3><p>Entreprise, activité et situation de départ, selon les informations publiables.</p></li><li><span>02</span><h3>Intervention</h3><p>Méthode, acteurs, périmètre et livrables réellement réalisés.</p></li><li><span>03</span><h3>Résultats</h3><p>Indicateurs avant/après vérifiés et limites d’interprétation.</p></li><li><span>04</span><h3>Retour</h3><p>Témoignage uniquement si le client l’autorise explicitement.</p></li></ol></div></section>
    <CTASection title="Votre projet peut devenir la prochaine réussite documentée." text="Commençons par clarifier le problème et le résultat que vous souhaitez obtenir." primaryLabel="Présenter mon projet" primaryHref="/contact" whatsappMessage={whatsappMessages.general} /></main>;
}
