import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Eye, Handshake, Target, Waypoints } from "lucide-react";
import { PageHero } from "@/app/_components/PageHero";
import { CTASection } from "@/app/_components/CTASection";
import { whatsappMessages } from "@/app/_lib/site";

export const metadata: Metadata = { title: "À propos de LIDA Solutions & Consulting", description: "Découvrez la vision, la mission, les valeurs et l’approche terrain de LIDA Solutions & Consulting au Maroc.", alternates: { canonical: "/a-propos" }, openGraph: { title: "À propos de LIDA Solutions & Consulting", description: "Un cabinet de conseil proche du terrain et orienté résultats.", url: "/a-propos", images: [{ url: "/photos/conseil.jpg", alt: "À propos de LIDA" }] } };

export default function AboutPage() {
  const values = [{ icon: Eye, title: "Clarté", text: "Rendre les enjeux compréhensibles avant de recommander une solution." }, { icon: Handshake, title: "Proximité", text: "Construire avec les dirigeants et les équipes, au plus près du terrain." }, { icon: Target, title: "Utilité", text: "Produire des outils et décisions qui améliorent réellement le travail." }, { icon: Waypoints, title: "Progression", text: "Mesurer, apprendre et renforcer ce qui fonctionne dans la durée." }];
  return <main><PageHero eyebrow="À propos" title="Un cabinet de conseil proche du terrain et orienté résultats." description="LIDA Solutions & Consulting accompagne les entreprises pour structurer leur organisation, digitaliser leurs pratiques, préparer les certifications ISO et développer les compétences." image="/photos/conseil.jpg" imageAlt="LIDA Solutions & Consulting, cabinet de conseil au Maroc" breadcrumbs={[{ label: "À propos", href: "/a-propos" }]} primaryLabel="Découvrir notre méthode" primaryHref="/a-propos/methodologie" whatsappMessage={whatsappMessages.general} />
    <section className="section"><div className="container two-column-sections"><div><p className="eyebrow eyebrow-dark"><span /> Vision</p><h2>Des entreprises mieux structurées, capables de progresser avec autonomie.</h2><p>LIDA défend une approche où les méthodes, les normes et les outils numériques restent au service du travail réel et des décisions.</p></div><div><p className="eyebrow eyebrow-dark"><span /> Mission</p><h2>Transformer les enjeux en systèmes simples et applicables.</h2><p>Diagnostic, feuille de route, déploiement, formation et mesure : chaque intervention vise une amélioration visible et durable.</p></div></div></section>
    <section className="section light-section"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow-dark"><span /> Nos valeurs</p><h2>Une exigence professionnelle sans complexité inutile.</h2></div><div className="feature-card-grid four-cols">{values.map(({ icon: Icon, title, text }) => <article className="feature-card" key={title}><Icon aria-hidden="true" size={24} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section"><div className="container consultant-profile"><div className="consultant-monogram"><span>AE</span><small>QHSE · ISO</small></div><div><p className="eyebrow eyebrow-dark"><span /> Votre consultant</p><h2>Adel El Haddioui</h2><p>Consultant senior QHSE, auditeur ISO 9001, ISO 14001 et ISO 45001, formateur professionnel et expert en systèmes de management.</p><Link className="text-link text-link-blue" href="/a-propos/adel-el-haddioui">Découvrir le parcours <ArrowRight aria-hidden="true" size={16} /></Link></div></div></section>
    <CTASection title="Construisons une intervention adaptée à votre réalité." text="Présentez votre besoin et vos priorités lors d’un premier échange." primaryLabel="Contacter LIDA" primaryHref="/contact" whatsappMessage={whatsappMessages.general} /></main>;
}
