import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { PageHero } from "@/app/_components/PageHero";
import { CTASection } from "@/app/_components/CTASection";
import { whatsappMessages } from "@/app/_lib/site";

export const metadata: Metadata = { title: "Adel El Haddioui — Consultant QHSE et ISO", description: "Présentation d’Adel El Haddioui, consultant senior QHSE, auditeur ISO et formateur professionnel chez LIDA.", alternates: { canonical: "/a-propos/adel-el-haddioui" }, openGraph: { title: "Adel El Haddioui — LIDA", description: "Consultant senior QHSE, auditeur ISO et formateur professionnel.", url: "/a-propos/adel-el-haddioui", images: [{ url: "/photos/iso.jpg", alt: "Expertise QHSE et ISO" }] } };

export default function ConsultantPage() {
  const expertises = ["Systèmes de management", "ISO 9001, ISO 14001 et ISO 45001", "Audit interne", "Formation QHSE", "Organisation et amélioration continue", "Accompagnement des dirigeants et équipes"];
  return <main><PageHero eyebrow="Votre consultant" title="Adel El Haddioui" description="Consultant senior QHSE, auditeur ISO 9001, ISO 14001 et ISO 45001, formateur professionnel et expert en systèmes de management." image="/photos/iso.jpg" imageAlt="Expertise QHSE et ISO chez LIDA" breadcrumbs={[{ label: "À propos", href: "/a-propos" }, { label: "Adel El Haddioui", href: "/a-propos/adel-el-haddioui" }]} primaryLabel="Prendre rendez-vous" primaryHref="/contact" whatsappMessage={whatsappMessages.general} />
    <section className="section"><div className="container two-column-sections"><div><p className="eyebrow eyebrow-dark"><span /> Positionnement</p><h2>Relier les exigences de management à la réalité opérationnelle.</h2><p>L’accompagnement combine lecture des référentiels, compréhension des activités, pédagogie et suivi des résultats. L’objectif n’est pas d’ajouter de la documentation, mais d’aider les équipes à mieux maîtriser leur fonctionnement.</p></div><div><p className="eyebrow eyebrow-dark"><span /> Domaines d’intervention</p><h2>Une expertise transversale.</h2><ul className="icon-list">{expertises.map((item) => <li key={item}><CheckCircle2 aria-hidden="true" size={19} />{item}</li>)}</ul></div></div></section>
    <section className="section light-section"><div className="container outcomes-layout"><div className="sticky-copy"><p className="eyebrow eyebrow-dark"><span /> Approche</p><h2>Écouter, structurer, transmettre.</h2></div><div className="benefit-list"><article><span>01</span><div><h3>Comprendre le contexte</h3><p>Les solutions partent des contraintes, ressources et objectifs réels.</p></div></article><article><span>02</span><div><h3>Construire avec les acteurs</h3><p>Les équipes participent aux choix qui modifient leur travail.</p></div></article><article><span>03</span><div><h3>Développer l’autonomie</h3><p>Les outils, méthodes et compétences restent dans l’entreprise.</p></div></article></div></div></section>
    <CTASection title="Échangez directement sur votre besoin." text="Un premier rendez-vous permet de cadrer les enjeux et le niveau d’accompagnement utile." primaryLabel="Demander un échange" primaryHref="/contact" whatsappMessage={whatsappMessages.general} /></main>;
}
