import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { PageHero } from "@/app/_components/PageHero";
import { CTASection } from "@/app/_components/CTASection";
import { whatsappMessages } from "@/app/_lib/site";

export const metadata: Metadata = { title: "Adel El Haddioui — Interlocuteur LIDA", description: "Découvrez l’approche d’Adel El Haddioui, interlocuteur de LIDA Solutions & Consulting pour les demandes de conseil et de formation.", alternates: { canonical: "/a-propos/adel-el-haddioui" }, openGraph: { title: "Adel El Haddioui — LIDA", description: "Une approche fondée sur l’écoute du terrain, des livrables explicites et le transfert aux équipes.", url: "/a-propos/adel-el-haddioui", images: [{ url: "/photos/pages/consultant.webp", alt: "Atelier de conseil et de formation" }] } };

export default function ConsultantPage() {
  const interventionAreas = ["Organisation et processus", "Digitalisation des flux de gestion", "Systèmes ISO 9001, ISO 14001 et ISO 45001", "Pilotage, risques et amélioration continue", "Formations professionnelles"];
  return <main><PageHero eyebrow="Votre interlocuteur" title="Adel El Haddioui" description="Interlocuteur de LIDA Solutions & Consulting pour comprendre votre situation, cadrer la demande et définir les livrables attendus." image="/photos/pages/consultant.webp" imageAlt="Atelier de conseil et de formation professionnelle" breadcrumbs={[{ label: "À propos", href: "/a-propos" }, { label: "Adel El Haddioui", href: "/a-propos/adel-el-haddioui" }]} primaryLabel="Prendre rendez-vous" primaryHref="/contact" whatsappMessage={whatsappMessages.general} />
    <section className="section"><div className="container two-column-sections"><div><p className="eyebrow eyebrow-dark"><span /> Positionnement</p><h2>Relier le besoin exprimé au fonctionnement réel.</h2><p>Le premier travail consiste à distinguer le symptôme, la cause probable et le résultat attendu. Le périmètre proposé précise ensuite les actions, les personnes à associer et les documents ou outils à remettre.</p></div><div><p className="eyebrow eyebrow-dark"><span /> Champs traités par LIDA</p><h2>Des sujets complémentaires.</h2><ul className="icon-list">{interventionAreas.map((item) => <li key={item}><CheckCircle2 aria-hidden="true" size={19} />{item}</li>)}</ul></div></div></section>
    <section className="section light-section"><div className="container outcomes-layout"><div className="sticky-copy"><p className="eyebrow eyebrow-dark"><span /> Approche</p><h2>Écouter, structurer, transmettre.</h2></div><div className="benefit-list"><article><span>01</span><div><h3>Comprendre le contexte</h3><p>Les solutions partent des contraintes, ressources et objectifs réels.</p></div></article><article><span>02</span><div><h3>Construire avec les acteurs</h3><p>Les équipes participent aux choix qui modifient leur travail.</p></div></article><article><span>03</span><div><h3>Développer l’autonomie</h3><p>Les outils, méthodes et compétences restent dans l’entreprise.</p></div></article></div></div></section>
    <CTASection title="Échangez directement sur votre besoin." text="Un premier rendez-vous permet de cadrer les enjeux et le niveau d’accompagnement utile." primaryLabel="Demander un échange" primaryHref="/contact" whatsappMessage={whatsappMessages.general} /></main>;
}
