import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Award, BookOpenCheck, CalendarDays, Check, ChevronRight, CirclePlay, ClipboardCheck, Clock3, FileText, GraduationCap, Layers3, MonitorPlay, Play, Sparkles, UserRoundCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { WhatsApp } from "@/components/WhatsApp";
import { FeaturedCourses } from "@/components/FeaturedCourses";

export const metadata:Metadata={title:"Formations professionnelles en ligne",description:"Développez des compétences utiles en entreprise avec les formations pratiques LIDA Formation."};

export default function Home(){return <><Header/><main>
  <section className="hero-modern"><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/><div className="container hero-modern-grid"><div className="hero-modern-copy reveal"><span className="hero-badge"><Sparkles/> Formations professionnelles <i/> 100 % en ligne</span><h1>Développez des compétences <span>qui font la différence.</span></h1><p>Des formations pratiques pour maîtriser les compétences réellement recherchées en entreprise.</p><div className="hero-actions"><Link href="/formations" className="button primary">Découvrir les formations <ArrowRight/></Link><a href="#fonctionnement" className="button ghost"><CirclePlay/> Comment ça marche ?</a></div><div className="hero-checks"><span><Check/>Cours en direct</span><span><Check/>Enregistrements disponibles</span><span><Check/>Supports & cas pratiques</span><span><Check/>Attestation de formation</span></div></div>
  <div className="hero-visual reveal"><div className="hero-photo"><Image src="/images/hero-learning-v2.png" alt="Professionnelle suivant une formation en ligne sur son ordinateur" fill priority unoptimized sizes="(max-width: 980px) 90vw, 45vw"/></div><div className="float-card session-card"><span className="float-icon"><CalendarDays/></span><div><small>Prochaine session</small><strong>Comptabilité pratique</strong></div></div><div className="float-card progress-card"><div className="progress-ring"><span>78%</span></div><div><small>Votre progression</small><strong>Excellent rythme</strong></div></div><div className="float-card certificate-card"><Award/><span>Attestation incluse</span></div><div className="live-pill"><i/> Cours en direct</div></div></div></section>

  <section className="section courses-section"><div className="container"><div className="section-heading split"><div><span className="section-kicker">Explorez nos parcours</span><h2>Des formations conçues pour <span>passer à l’action</span></h2></div><p>Des contenus structurés, des cas concrets et un accompagnement pour progresser étape par étape.</p></div><FeaturedCourses/></div></section>

  <section className="section why-section" id="pourquoi"><div className="container"><div className="section-heading centered"><span className="section-kicker light">Pourquoi LIDA Formation ?</span><h2>Une expérience pensée pour votre progression</h2><p>Apprendre, pratiquer, échanger et valider vos acquis dans un environnement simple et stimulant.</p></div><div className="why-grid">{[[BookOpenCheck,"Apprentissage pratique","Des cas réels et exercices applicables en entreprise."],[MonitorPlay,"Cours en direct","Échangez directement avec le formateur pendant les sessions."],[FileText,"Accès aux supports","Retrouvez supports, vidéos et exercices depuis votre espace."],[UserRoundCheck,"Accompagnement","Suivez votre progression tout au long du parcours."]].map(([Icon,title,text],i)=><article key={String(title)} className="why-card"><span className="why-number">0{i+1}</span><span className="why-icon"><Icon/></span><h3>{String(title)}</h3><p>{String(text)}</p><ChevronRight/></article>)}</div></div></section>

  <section className="section steps-section" id="fonctionnement"><div className="container"><div className="section-heading centered"><span className="section-kicker">Un parcours clair</span><h2>Comment ça marche ?</h2><p>Quatre étapes simples pour transformer votre projet en compétences concrètes.</p></div><div className="steps-timeline">{[[Layers3,"Choisissez votre formation","Trouvez le parcours adapté à votre objectif."],[ClipboardCheck,"Inscrivez-vous","Transmettez votre demande en quelques minutes."],[Play,"Suivez vos cours","Participez aux directs et avancez avec les supports."],[GraduationCap,"Obtenez votre attestation","Validez votre parcours et vos nouvelles compétences."]].map(([Icon,title,text],i)=><article key={String(title)}><div className="step-top"><span>{String(i+1).padStart(2,"0")}</span><i/></div><div className="step-icon"><Icon/></div><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></div></section>

  <section className="section platform-section"><div className="container platform-grid"><div className="platform-mockup reveal"><div className="mockup-bar"><div className="mockup-brand"><span>L</span><strong>LIDA</strong></div><span className="mockup-user">NB</span></div><div className="mockup-body"><aside><i className="active"><Layers3/></i><i><CalendarDays/></i><i><FileText/></i><i><ClipboardCheck/></i><i><Award/></i></aside><div className="mockup-content"><small>Bonjour Nadia 👋</small><h3>Continuez votre progression</h3><div className="mockup-stats"><span><b>3</b> Formations</span><span><b>62%</b> Progression</span><span><b>2</b> Sessions</span></div><div className="mockup-course"><div className="mockup-thumb"/><div><strong>Comptabilité générale</strong><small>Module 7 sur 10</small><div className="mockup-progress"><i/></div></div><b>65%</b></div><div className="mockup-course"><div className="mockup-thumb second"/><div><strong>Excel professionnel</strong><small>Module 5 sur 6</small><div className="mockup-progress"><i style={{width:"80%"}}/></div></div><b>80%</b></div></div></div></div><div className="platform-copy"><span className="section-kicker">Votre espace personnel</span><h2>Tout votre parcours <span>au même endroit</span></h2><p>Cours, supports, exercices, QCM, progression et attestations depuis une interface pensée pour apprendre sans friction.</p><div className="platform-features">{[[Layers3,"Mes formations"],[CalendarDays,"Agenda"],[FileText,"Supports"],[ClipboardCheck,"QCM"],[Clock3,"Progression"],[Award,"Attestations"]].map(([Icon,label])=><span key={String(label)}><i><Icon/></i>{String(label)}</span>)}</div><Link href="/connexion" className="text-link">Découvrir l’espace stagiaire <ArrowRight/></Link></div></div></section>

  <section className="final-cta"><div className="cta-shape one"/><div className="cta-shape two"/><div className="container"><div><span>Commencez votre parcours</span><h2>Prêt à développer vos compétences ?</h2><p>Choisissez votre formation et commencez votre parcours avec LIDA Formation.</p></div><div className="cta-actions"><Link href="/formations" className="button gold-button">Découvrir les formations <ArrowRight/></Link><Link href="/contact" className="button outline-light">Nous contacter</Link></div></div></section>
</main><Footer/><WhatsApp/></>}
