-- LIDA Formation - initial LMS schema for Supabase/PostgreSQL
create extension if not exists pgcrypto;

create type public.app_role as enum ('admin','trainer','student');
create type public.content_status as enum ('draft','published','archived');
create type public.enrollment_status as enum ('active','pending','expired','cancelled');
create type public.progress_status as enum ('not_started','in_progress','completed');
create type public.payment_status as enum ('paid','partial','pending','cancelled');
create type public.session_status as enum ('upcoming','live','completed','cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '', last_name text not null default '', phone text, city text,
  avatar_path text, organization text, profession text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null default 'student', primary key(user_id,role)
);
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, created_at timestamptz not null default now());
create table public.trainers (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles(id) on delete set null, bio text, title text, expertise text[] not null default '{}', is_published boolean not null default false);
create table public.courses (
  id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, description text not null default '', short_description text not null default '',
  category_id uuid references public.categories(id) on delete set null, level text not null, duration_minutes integer not null check(duration_minutes > 0), session_count integer not null default 0 check(session_count >= 0),
  price numeric(12,2) not null default 0 check(price >= 0), old_price numeric(12,2) check(old_price is null or old_price >= price), image_path text, status public.content_status not null default 'draft',
  trainer_id uuid references public.trainers(id) on delete set null, certificate_enabled boolean not null default true, featured boolean not null default false, prerequisites text, target_audience text,
  objectives text[] not null default '{}', format text not null default 'online', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.modules (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, title text not null, description text, position integer not null check(position >= 0), is_published boolean not null default false, unique(course_id,position));
create table public.chapters (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.modules(id) on delete cascade, title text not null, position integer not null check(position >= 0), unique(module_id,position));
create table public.lessons (id uuid primary key default gen_random_uuid(), chapter_id uuid not null references public.chapters(id) on delete cascade, title text not null, description text, content text, video_provider text, video_url text, duration_minutes integer check(duration_minutes is null or duration_minutes >= 0), position integer not null check(position >= 0), is_published boolean not null default false, unique(chapter_id,position));
create table public.lesson_resources (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.lessons(id) on delete cascade, title text not null, resource_type text not null check(resource_type in ('pdf','excel','word','powerpoint','image','link','other')), storage_path text, external_url text, is_downloadable boolean not null default true, created_at timestamptz not null default now(), check((storage_path is not null)::int + (external_url is not null)::int = 1));
create table public.enrollments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, course_id uuid not null references public.courses(id) on delete cascade, status public.enrollment_status not null default 'pending', start_date date, end_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,course_id), check(end_date is null or start_date is null or end_date >= start_date));
create table public.lesson_progress (user_id uuid not null references public.profiles(id) on delete cascade, lesson_id uuid not null references public.lessons(id) on delete cascade, status public.progress_status not null default 'not_started', progress_percent smallint not null default 0 check(progress_percent between 0 and 100), started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now(), primary key(user_id,lesson_id));
create table public.quizzes (id uuid primary key default gen_random_uuid(), lesson_id uuid references public.lessons(id) on delete cascade, course_id uuid not null references public.courses(id) on delete cascade, title text not null, passing_score smallint not null default 60 check(passing_score between 0 and 100), max_attempts smallint check(max_attempts is null or max_attempts > 0), show_corrections boolean not null default true, is_published boolean not null default false, created_at timestamptz not null default now());
create table public.quiz_questions (id uuid primary key default gen_random_uuid(), quiz_id uuid not null references public.quizzes(id) on delete cascade, prompt text not null, explanation text, points numeric(8,2) not null default 1 check(points > 0), position integer not null check(position >= 0), allows_multiple boolean not null default false, unique(quiz_id,position));
create table public.quiz_answers (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.quiz_questions(id) on delete cascade, label text not null, is_correct boolean not null default false, position integer not null check(position between 0 and 5), unique(question_id,position));
create table public.quiz_attempts (id uuid primary key default gen_random_uuid(), quiz_id uuid not null references public.quizzes(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, attempt_number smallint not null check(attempt_number > 0), score numeric(10,2) not null default 0, percentage numeric(5,2) not null default 0 check(percentage between 0 and 100), submitted_at timestamptz, created_at timestamptz not null default now(), unique(quiz_id,user_id,attempt_number));
create table public.quiz_attempt_answers (attempt_id uuid not null references public.quiz_attempts(id) on delete cascade, question_id uuid not null references public.quiz_questions(id) on delete cascade, answer_id uuid not null references public.quiz_answers(id) on delete cascade, is_correct boolean not null default false, points_awarded numeric(8,2) not null default 0, primary key(attempt_id,question_id,answer_id));
create table public.assignments (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.lessons(id) on delete cascade, title text not null, instructions text, attachment_path text, due_at timestamptz, allows_upload boolean not null default true, created_at timestamptz not null default now());
create table public.assignment_submissions (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references public.assignments(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, answer_text text, file_path text, status text not null default 'submitted', grade numeric(8,2), feedback text, submitted_at timestamptz not null default now(), unique(assignment_id,user_id));
create table public.course_sessions (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, module_id uuid references public.modules(id) on delete set null, trainer_id uuid references public.trainers(id) on delete set null, title text not null, starts_at timestamptz not null, ends_at timestamptz not null, meeting_url text, status public.session_status not null default 'upcoming', check(ends_at > starts_at));
create table public.payments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete restrict, course_id uuid not null references public.courses(id) on delete restrict, total_amount numeric(12,2) not null check(total_amount >= 0), paid_amount numeric(12,2) not null default 0 check(paid_amount >= 0 and paid_amount <= total_amount), payment_date date, method text, reference text unique, status public.payment_status not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.certificates (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete restrict, course_id uuid not null references public.courses(id) on delete restrict, certificate_number text not null unique, issued_at date, duration_label text, file_path text, verification_token uuid not null default gen_random_uuid() unique, status text not null default 'pending', unique(user_id,course_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, type text not null, action_url text, read_at timestamptz, created_at timestamptz not null default now());
create table public.registration_requests (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, phone text not null, whatsapp text, email text not null, city text, desired_course_id uuid references public.courses(id) on delete set null, professional_status text, message text, status text not null default 'new', created_at timestamptz not null default now());
create table public.testimonials (id uuid primary key default gen_random_uuid(), author_name text not null, author_title text, quote text not null, rating smallint check(rating between 1 and 5), is_published boolean not null default false, created_at timestamptz not null default now());
create table public.settings (key text primary key, value jsonb not null, is_public boolean not null default false, updated_at timestamptz not null default now());

create index courses_status_category_idx on public.courses(status,category_id); create index modules_course_idx on public.modules(course_id,position); create index enrollments_user_status_idx on public.enrollments(user_id,status); create index enrollments_course_status_idx on public.enrollments(course_id,status); create index progress_user_idx on public.lesson_progress(user_id,status); create index sessions_course_start_idx on public.course_sessions(course_id,starts_at); create index payments_user_idx on public.payments(user_id,status); create index notifications_user_unread_idx on public.notifications(user_id,read_at);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role='admin') $$;
create or replace function public.is_trainer_for_course(target_course uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.courses c join public.trainers t on t.id=c.trainer_id where c.id=target_course and t.profile_id=auth.uid()) $$;
create or replace function public.has_course_access(target_course uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin() or public.is_trainer_for_course(target_course) or exists(select 1 from public.enrollments where user_id=auth.uid() and course_id=target_course and status='active' and (end_date is null or end_date>=current_date)) $$;

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.categories enable row level security; alter table public.trainers enable row level security; alter table public.courses enable row level security; alter table public.modules enable row level security; alter table public.chapters enable row level security; alter table public.lessons enable row level security; alter table public.lesson_resources enable row level security; alter table public.enrollments enable row level security; alter table public.lesson_progress enable row level security; alter table public.quizzes enable row level security; alter table public.quiz_questions enable row level security; alter table public.quiz_answers enable row level security; alter table public.quiz_attempts enable row level security; alter table public.quiz_attempt_answers enable row level security; alter table public.assignments enable row level security; alter table public.assignment_submissions enable row level security; alter table public.course_sessions enable row level security; alter table public.payments enable row level security; alter table public.certificates enable row level security; alter table public.notifications enable row level security; alter table public.registration_requests enable row level security; alter table public.testimonials enable row level security; alter table public.settings enable row level security;

create policy "public published courses" on public.courses for select using(status='published' or public.has_course_access(id));
create policy "public categories" on public.categories for select using(true); create policy "public trainers" on public.trainers for select using(is_published or public.is_admin()); create policy "public testimonials" on public.testimonials for select using(is_published or public.is_admin()); create policy "public settings" on public.settings for select using(is_public or public.is_admin());
create policy "own profile read" on public.profiles for select using(id=auth.uid() or public.is_admin()); create policy "own profile update" on public.profiles for update using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy "own roles read" on public.user_roles for select using(user_id=auth.uid() or public.is_admin());
create policy "own enrollment read" on public.enrollments for select using(user_id=auth.uid() or public.is_admin() or public.is_trainer_for_course(course_id));
create policy "authorized modules" on public.modules for select using(public.has_course_access(course_id));
create policy "authorized chapters" on public.chapters for select using(exists(select 1 from public.modules m where m.id=module_id and public.has_course_access(m.course_id)));
create policy "authorized lessons" on public.lessons for select using(exists(select 1 from public.chapters c join public.modules m on m.id=c.module_id where c.id=chapter_id and public.has_course_access(m.course_id)));
create policy "authorized resources" on public.lesson_resources for select using(exists(select 1 from public.lessons l join public.chapters c on c.id=l.chapter_id join public.modules m on m.id=c.module_id where l.id=lesson_id and public.has_course_access(m.course_id)));
create policy "own progress" on public.lesson_progress for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "authorized quizzes" on public.quizzes for select using(public.has_course_access(course_id));
create policy "own attempts" on public.quiz_attempts for select using(user_id=auth.uid() or public.is_admin() or public.is_trainer_for_course((select course_id from public.quizzes where id=quiz_id)));
create policy "own attempt insert" on public.quiz_attempts for insert with check(user_id=auth.uid() and public.has_course_access((select course_id from public.quizzes where id=quiz_id)));
create policy "own submissions" on public.assignment_submissions for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "own payments" on public.payments for select using(user_id=auth.uid() or public.is_admin()); create policy "own certificates" on public.certificates for select using(user_id=auth.uid() or public.is_admin()); create policy "own notifications" on public.notifications for select using(user_id=auth.uid() or public.is_admin()); create policy "own notification update" on public.notifications for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "public registration insert" on public.registration_requests for insert with check(true);

-- Admin management policies are explicit and keep RLS enabled.
do $$ declare t text; begin foreach t in array array['categories','trainers','courses','modules','chapters','lessons','lesson_resources','enrollments','quizzes','quiz_questions','quiz_answers','assignments','course_sessions','payments','certificates','notifications','testimonials','settings','registration_requests'] loop execute format('create policy "admin manage %1$s" on public.%1$I for all using (public.is_admin()) with check (public.is_admin())',t); end loop; end $$;

-- Private Storage bucket. Generate signed URLs only after authorization.
insert into storage.buckets(id,name,public,file_size_limit) values('private-course-files','private-course-files',false,52428800) on conflict(id) do nothing;
create policy "authorized private files" on storage.objects for select using(bucket_id='private-course-files' and (public.is_admin() or exists(select 1 from public.lesson_resources r join public.lessons l on l.id=r.lesson_id join public.chapters c on c.id=l.chapter_id join public.modules m on m.id=c.module_id where r.storage_path=name and public.has_course_access(m.course_id))));

insert into public.settings(key,value,is_public) values('whatsapp_number','"212600000000"'::jsonb,true) on conflict(key) do nothing;
