import { notFound } from "next/navigation";
import { Bell, Plus, Search } from "lucide-react";
import { DashboardShell } from "@/components/DashboardShell";

const sections: Record<string,{title:string;subtitle:string;columns:string[];rows:string[][];action:string}> = {
  formations:{title:"Formations",subtitle:"Créez, publiez et organisez votre catalogue.",columns:["Formation","Catégorie","Modules","Prix","Statut"],rows:[["Comptabilité générale","Finance","10","2 400 MAD","Publié"],["Fiscalité marocaine","Fiscalité","5","2 200 MAD","Publié"],["Sage 100","Logiciels","7","1 900 MAD","Brouillon"]],action:"Nouvelle formation"},
  stagiaires:{title:"Stagiaires",subtitle:"Gérez les accès, paiements et progressions.",columns:["Nom","Formation","Paiement","Progression","Statut"],rows:[["Nadia Berrada","Comptabilité","Payé","65 %","Actif"],["Youssef Amrani","Fiscalité","Partiel","42 %","Actif"],["Sara Kettani","Sage 100","En attente","0 %","En attente"]],action:"Ajouter un stagiaire"},
  formateurs:{title:"Formateurs",subtitle:"Gérez l'équipe pédagogique et ses affectations.",columns:["Formateur","Expertise","Formations","Sessions","Statut"],rows:[["Amine El Idrissi","Comptabilité","3","8","Actif"],["Salma Bennani","Fiscalité","2","5","Actif"]],action:"Ajouter un formateur"},
  agenda:{title:"Agenda",subtitle:"Planifiez les sessions et les liens de visioconférence.",columns:["Session","Formation","Date","Formateur","Statut"],rows:[["TVA","Fiscalité","04/08 · 18h30","S. Bennani","À venir"],["Inventaire","Comptabilité","07/08 · 19h00","A. El Idrissi","À venir"]],action:"Nouvelle séance"},
  qcm:{title:"QCM",subtitle:"Créez les évaluations et suivez les tentatives.",columns:["QCM","Formation","Questions","Tentatives","Statut"],rows:[["Principes comptables","Comptabilité","12","48","Publié"],["TVA","Fiscalité","15","31","Publié"]],action:"Nouveau QCM"},
  documents:{title:"Documents",subtitle:"Gérez les supports privés de la plateforme.",columns:["Document","Type","Formation","Taille","Statut"],rows:[["Guide TVA","PDF","Fiscalité","2,4 Mo","Privé"],["Cas Atlas","Excel","Comptabilité","680 Ko","Privé"]],action:"Ajouter un document"},
  paiements:{title:"Paiements",subtitle:"Suivez les règlements et les restes à payer.",columns:["Stagiaire","Formation","Total","Payé","Statut"],rows:[["Nadia Berrada","Comptabilité","2 400 MAD","2 400 MAD","Payé"],["Youssef Amrani","Fiscalité","2 200 MAD","1 100 MAD","Partiel"]],action:"Enregistrer un paiement"},
  attestations:{title:"Attestations",subtitle:"Validez et distribuez les attestations.",columns:["Stagiaire","Formation","Numéro","Date","Statut"],rows:[["Nadia Berrada","Excel professionnel","LF-2026-0184","28/07/2026","Disponible"]],action:"Nouvelle attestation"},
  parametres:{title:"Paramètres",subtitle:"Configurez les informations générales de la plateforme.",columns:["Paramètre","Valeur","Visibilité","Mise à jour","Statut"],rows:[["WhatsApp","+212 6 00 00 00 00","Public","02/08/2026","Actif"],["Email","contact@lidasol.com","Public","02/08/2026","Actif"]],action:"Modifier les paramètres"},
};

export default async function AdminSection({params}:{params:Promise<{section:string}>}) { const {section}=await params; const data=sections[section]; if(!data) notFound(); return <DashboardShell admin><header className="dash-header"><div><small>ADMINISTRATION</small><h1>{data.title}</h1></div><div className="dash-user"><Bell size={18}/><span>AD</span></div></header><div className="dash-section-title"><div><h2>{data.title}</h2><p className="dash-subtitle">{data.subtitle}</p></div><button className="button primary" type="button"><Plus size={17}/>{data.action}</button></div><section className="dash-card"><div className="admin-toolbar"><div className="search-wrap"><Search/><input className="field" placeholder={`Rechercher dans ${data.title.toLowerCase()}...`} aria-label={`Rechercher dans ${data.title.toLowerCase()}`}/></div></div><div className="table-scroll"><table className="admin-table"><thead><tr>{data.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{data.rows.map((row,i)=><tr key={`${section}-${i}`}>{row.map((value,j)=><td key={`${i}-${j}`}>{j===row.length-1?<span className="status-pill">{value}</span>:value}</td>)}</tr>)}</tbody></table></div></section></DashboardShell>; }
