import type { Metadata } from "next";
import { PageHero } from "@/app/_components/PageHero";
import { CTASection } from "@/app/_components/CTASection";
import { whatsappMessages } from "@/app/_lib/site";

export const metadata: Metadata = { title: "Méthodologie d’accompagnement LIDA", description: "La méthode LIDA : cadrage, diagnostic, feuille de route, déploiement avec les équipes et mesure des résultats.", alternates: { canonical: "/a-propos/methodologie" }, openGraph: { title: "La méthodologie LIDA", description: "Cadrer, diagnostiquer, prioriser, déployer et mesurer avec les équipes.", url: "/a-propos/methodologie", images: [{ url: "/photos/organisation.jpg", alt: "Méthodologie LIDA" }] } };

export default function MethodPage() {
  const steps = [{ title: "Cadrer le résultat", text: "Clarifier le besoin, le périmètre, les décideurs et les critères de réussite." }, { title: "Observer le terrain", text: "Croiser entretiens, pratiques, données et documents existants." }, { title: "Prioriser", text: "Distinguer l’urgent, l’important et ce qui peut attendre." }, { title: "Co-construire", text: "Créer les outils et nouvelles pratiques avec les personnes concernées." }, { title: "Déployer", text: "Accompagner l’application, former et lever les difficultés." }, { title: "Mesurer et ajuster", text: "Suivre les résultats, corriger les écarts et transmettre l’autonomie." }];
  return <main><PageHero eyebrow="Méthodologie" title="De l’idée au résultat, sans perdre le terrain." description="Une démarche progressive, collaborative et orientée action, avec une vision claire de l’avancement à chaque étape." image="/photos/organisation.jpg" imageAlt="Méthodologie d’accompagnement LIDA" breadcrumbs={[{ label: "À propos", href: "/a-propos" }, { label: "Méthodologie", href: "/a-propos/methodologie" }]} primaryLabel="Présenter mon besoin" primaryHref="/contact" whatsappMessage={whatsappMessages.diagnostic} />
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow-dark"><span /> Les étapes</p><h2>Une progression lisible du diagnostic à l’autonomie.</h2></div><ol className="method-timeline">{steps.map((step, index) => <li key={step.title}><span>0{index + 1}</span><div><h2>{step.title}</h2><p>{step.text}</p></div></li>)}</ol></div></section>
    <section className="section light-section"><div className="container two-column-sections"><div><p className="eyebrow eyebrow-dark"><span /> Gouvernance</p><h2>Des décisions au bon niveau.</h2><p>Le sponsor, les responsables et les contributeurs sont identifiés dès le départ. Les points de suivi servent à arbitrer et agir.</p></div><div><p className="eyebrow eyebrow-dark"><span /> Mesure</p><h2>Des résultats observables.</h2><p>Les indicateurs sont choisis en fonction du projet : délai, qualité, charge, conformité, adoption ou progression des compétences.</p></div></div></section>
    <CTASection title="Appliquons cette méthode à votre priorité." text="L’intervention commence par un cadrage proportionné, sans engagement inutile." primaryLabel="Demander un diagnostic" primaryHref="/contact" whatsappMessage={whatsappMessages.diagnostic} /></main>;
}
